/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font47.c                                              *
* Font:        Î¢ÈíÑÅºÚ                                              *
* Height:      47                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  47                                           *
* Range disabled:       0000 - FFFF                                  *
* Range enabled:        0030 - 0099                                  *
* Character disabled:  0x7B (123)                                    *
* Character disabled:  0x7C (124)                                    *
* Character disabled:  0x7D (125)                                    *
* Character disabled:  0x7E (126)                                    *
* Character disabled:  0x7F (127)                                    *
* Character disabled:  0x5B (91)                                     *
* Character disabled:  0x5C (92)                                     *
* Character disabled:  0x5D (93)                                     *
* Character disabled:  0x5E (94)                                     *
* Character disabled:  0x5F (95)                                     *
* Character disabled:  0x60 (96)                                     *
* Character disabled:  0x40 (64)                                     *
* Character disabled:  0x3B (59)                                     *
* Character disabled:  0x3C (60)                                     *
* Character disabled:  0x3D (61)                                     *
* Character disabled:  0x3E (62)                                     *
* Character enabled:   0x3E (62)                                     *
* Character disabled:  0x3F (63)                                     *
* Character disabled:  0x3E (62)                                     *
* Character enabled:   0x2B (43)                                     *
* Character enabled:   0x2D (45)                                     *
* Edit/Insert/Left      at character 0x30 (48)                       *
* Edit/Delete/Left      at character 0x30 (48)                       *
* Save pattern file: C:\Users\ChxxxXL\Downloads\en.stm32cubef4_v1-26-0\STM32Cube_FW_F4_V1.26.0\Middlewares\ST\STemWin\Software\qqq.txt*
* Character enabled:   0x5F85 (24453)                                *
* Character disabled:  0x5F85 (24453)                                *
* Character enabled:   0x5F85 (24453)                                *
* Character enabled:   0x7F8E (32654)                                *
* Character disabled:  0x7F8E (32654)                                *
* Character enabled:   0x7F8E (32654)                                *
* Character disabled:  0x7F8E (32654)                                *
* Character enabled:   0x7F8E (32654)                                *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ChxxxXL\Downloads\en.stm32cubef4_v1-26-0\STM32Cube_FW_F4_V1.26.0\Middlewares\ST\STemWin\Software\Font.txt*
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ChxxxXL\Downloads\en.stm32cubef4_v1-26-0\STM32Cube_FW_F4_V1.26.0\Middlewares\ST\STemWin\Software\Font.txt*
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ChxxxXL\Downloads\en.stm32cubef4_v1-26-0\STM32Cube_FW_F4_V1.26.0\Middlewares\ST\STemWin\Software\Font.txt*
* Character enabled:   0x40 (64)                                     *
* Character enabled:   0x30 (48)                                     *
* Character disabled:  0x40 (64)                                     *
* Save pattern file: C:\Users\ChxxxXL\Desktop\aaa.txt                *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ChxxxXL\Downloads\en.stm32cubef4_v1-26-0\STM32Cube_FW_F4_V1.26.0\Middlewares\ST\STemWin\Software\Font.txt*
* Read pattern file: C:\Users\ChxxxXL\Downloads\en.stm32cubef4_v1-26-0\STM32Cube_FW_F4_V1.26.0\Middlewares\ST\STemWin\Software\Font.txt*
* Read pattern file: C:\Users\ChxxxXL\Downloads\en.stm32cubef4_v1-26-0\STM32Cube_FW_F4_V1.26.0\Middlewares\ST\STemWin\Software\Font.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_Font47;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont47_002B[ 54] = { /* code 002B, PLUS SIGN */
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________,
  _______X,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_002D[  8] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_002E[  6] = { /* code 002E, FULL STOP */
  __XXX___,
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0030[ 84] = { /* code 0030, DIGIT ZERO */
  _______X,XXXXXX__,________,
  _____XXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  __XXXXXX,X___XXXX,XX______,
  __XXXXXX,_____XXX,XXX_____,
  _XXXXXX_,_____XXX,XXX_____,
  _XXXXXX_,_____XXX,XXX_____,
  _XXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXXXX___,
  XXXXXX__,______XX,XXX_____,
  _XXXXXX_,_____XXX,XXX_____,
  _XXXXXX_,_____XXX,XXX_____,
  _XXXXXX_,_____XXX,XX______,
  __XXXXXX,____XXXX,XX______,
  __XXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXX_,________,
  ______XX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0031[ 56] = { /* code 0031, DIGIT ONE */
  _______X,XXXX____,
  ______XX,XXXX____,
  ____XXXX,XXXX____,
  __XXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXXXXXX,XXXX____,
  XXXX__XX,XXXX____,
  XX____XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____,
  ______XX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0032[ 84] = { /* code 0032, DIGIT TWO */
  _____XXX,XXXXX___,________,
  __XXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _XXXX___,__XXXXXX,X_______,
  _XX_____,___XXXXX,XX______,
  ________,____XXXX,XX______,
  ________,____XXXX,XX______,
  ________,____XXXX,XX______,
  ________,____XXXX,XX______,
  ________,___XXXXX,XX______,
  ________,___XXXXX,X_______,
  ________,__XXXXXX,X_______,
  ________,_XXXXXXX,________,
  ________,XXXXXXXX,________,
  _______X,XXXXXXX_,________,
  _____XXX,XXXXX___,________,
  ____XXXX,XXXX____,________,
  ___XXXXX,XXX_____,________,
  __XXXXXX,XX______,________,
  __XXXXXX,X_______,________,
  _XXXXXXX,________,________,
  _XXXXXX_,________,________,
  XXXXXXX_,________,________,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0033[ 84] = { /* code 0033, DIGIT THREE */
  ____XXXX,XXXX____,________,
  _XXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXX_,________,
  _XXXXXXX,XXXXXXXX,________,
  _XXX____,_XXXXXXX,X_______,
  _X______,__XXXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,__XXXXXX,________,
  ________,_XXXXXX_,________,
  ___XXXXX,XXXXXX__,________,
  ___XXXXX,XXXX____,________,
  ___XXXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXX_,________,
  ________,XXXXXXXX,________,
  ________,__XXXXXX,________,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  X_______,__XXXXXX,X_______,
  XXX_____,_XXXXXXX,________,
  XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXX___,________,
  __XXXXXX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0034[ 84] = { /* code 0034, DIGIT FOUR */
  ________,____XXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,__XXXXXX,X_______,
  ________,__XXXXXX,X_______,
  ________,_XXXXXXX,X_______,
  ________,XXXXXXXX,X_______,
  ________,XXXXXXXX,X_______,
  _______X,XXX_XXXX,X_______,
  ______XX,XXX_XXXX,X_______,
  ______XX,XX__XXXX,X_______,
  _____XXX,XX__XXXX,X_______,
  ____XXXX,X___XXXX,X_______,
  ____XXXX,____XXXX,X_______,
  ___XXXXX,____XXXX,X_______,
  __XXXXX_,____XXXX,X_______,
  _XXXXX__,____XXXX,X_______,
  XXXXX___,____XXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,____XXXX,X_______,
  ________,____XXXX,X_______,
  ________,____XXXX,X_______,
  ________,____XXXX,X_______,
  ________,____XXXX,X_______,
  ________,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0035[ 84] = { /* code 0035, DIGIT FIVE */
  _XXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,________,
  _XXXX___,________,________,
  _XXXX___,________,________,
  _XXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXX___,________,________,
  XXXXXXXX,XXX_____,________,
  XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,________,
  ________,XXXXXXXX,________,
  ________,__XXXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,X_______,
  ________,__XXXXXX,X_______,
  ________,__XXXXXX,________,
  XXX_____,XXXXXXXX,________,
  XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,
  XXXXXXXX,XXXXX___,________,
  __XXXXXX,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0036[ 84] = { /* code 0036, DIGIT SIX */
  ________,_XXXXXXX,________,
  ______XX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XX______,X_______,
  __XXXXXX,X_______,________,
  __XXXXXX,________,________,
  _XXXXXX_,________,________,
  _XXXXXX_,________,________,
  _XXXXX__,________,________,
  XXXXXX__,_XXXXX__,________,
  XXXXXX_X,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,___XXXXX,XX______,
  XXXXXXX_,____XXXX,XXX_____,
  XXXXXX__,_____XXX,XXX_____,
  XXXXXX__,_____XXX,XXX_____,
  XXXXXX__,_____XXX,XXX_____,
  XXXXXX__,_____XXX,XXX_____,
  _XXXXX__,_____XXX,XXX_____,
  _XXXXXX_,_____XXX,XXX_____,
  _XXXXXX_,____XXXX,XX______,
  __XXXXXX,___XXXXX,XX______,
  __XXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXX_,________,
  ______XX,XXXXX___,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0037[ 84] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  XXXXXXXX,XXXXXXXX,XXX_____,
  ________,_____XXX,XX______,
  ________,____XXXX,XX______,
  ________,____XXXX,X_______,
  ________,___XXXXX,X_______,
  ________,___XXXXX,________,
  ________,__XXXXXX,________,
  ________,_XXXXXX_,________,
  ________,_XXXXXX_,________,
  ________,_XXXXX__,________,
  ________,XXXXXX__,________,
  ________,XXXXX___,________,
  _______X,XXXXX___,________,
  _______X,XXXXX___,________,
  ______XX,XXXX____,________,
  ______XX,XXXX____,________,
  ______XX,XXXX____,________,
  _____XXX,XXX_____,________,
  _____XXX,XXX_____,________,
  _____XXX,XXX_____,________,
  _____XXX,XXX_____,________,
  ____XXXX,XX______,________,
  ____XXXX,XX______,________,
  ____XXXX,XX______,________,
  ____XXXX,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0038[ 84] = { /* code 0038, DIGIT EIGHT */
  ______XX,XXXX____,________,
  ____XXXX,XXXXXX__,________,
  ___XXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXX_,___XXXXX,________,
  _XXXXXX_,___XXXXX,X_______,
  _XXXXX__,____XXXX,X_______,
  _XXXXX__,____XXXX,X_______,
  _XXXXX__,____XXXX,X_______,
  _XXXXX__,____XXXX,X_______,
  __XXXXX_,___XXXXX,________,
  ___XXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXX__,________,
  _____XXX,XXXXX___,________,
  ___XXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,________,
  _XXXXX__,___XXXXX,X_______,
  _XXXXX__,____XXXX,XX______,
  XXXXX___,_____XXX,XX______,
  XXXXX___,_____XXX,XX______,
  XXXXX___,_____XXX,XX______,
  XXXXX___,_____XXX,XX______,
  XXXXXX__,____XXXX,XX______,
  _XXXXXX_,___XXXXX,X_______,
  _XXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXX_,________,
  ______XX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0039[ 84] = { /* code 0039, DIGIT NINE */
  ______XX,XXXXX___,________,
  ____XXXX,XXXXXXX_,________,
  ___XXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,___XXXXX,X_______,
  _XXXXXX_,____XXXX,XX______,
  XXXXXX__,____XXXX,XX______,
  XXXXXX__,_____XXX,XX______,
  XXXXXX__,_____XXX,XXX_____,
  XXXXXX__,_____XXX,XXX_____,
  XXXXXX__,_____XXX,XXX_____,
  XXXXXX__,_____XXX,XXX_____,
  XXXXXXX_,____XXXX,XXX_____,
  _XXXXXXX,___XXXXX,XXX_____,
  _XXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXX_XXX,XXX_____,
  _____XXX,XXX__XXX,XXX_____,
  ________,_____XXX,XX______,
  ________,_____XXX,XX______,
  ________,____XXXX,XX______,
  ________,____XXXX,X_______,
  ________,___XXXXX,X_______,
  __X_____,__XXXXXX,________,
  __XXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXX___,________,
  ___XXXXX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_003A[ 20] = { /* code 003A, COLON */
  __XXXX__,
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_,
  _XXXXX__,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  __XXX___,
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_,
  XXXXXXX_,
  __XXXX__};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_0073[ 40] = { /* code 0073, LATIN SMALL LETTER S */
  _____XXX,XXXXX___,
  ___XXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXX__,
  XXXXXXX_,_____X__,
  XXXXXX__,________,
  XXXXXX__,________,
  XXXXXXX_,________,
  XXXXXXXX,XX______,
  _XXXXXXX,XXXX____,
  __XXXXXX,XXXXXX__,
  ____XXXX,XXXXXX__,
  _______X,XXXXXXX_,
  ________,_XXXXXX_,
  X_______,_XXXXXX_,
  XXX_____,XXXXXXX_,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXX____,
  __XXXXXX,XX______};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont47_4F4D[170] = { /* code 4F4D */
  _______X,X_______,______XX,________,________,
  _______X,XXXX____,___XXXXX,X_______,________,
  _______X,XXXX____,____XXXX,X_______,________,
  ______XX,XXX_____,____XXXX,XX______,________,
  ______XX,XXX_____,____XXXX,XX______,________,
  ______XX,XXX_____,_____XXX,XX______,________,
  _____XXX,XX__XXXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XXX,XX__XXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,X___XXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,X___XXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,X_______,________,________,________,
  ___XXXXX,X_______,X_______,____X___,________,
  ___XXXXX,X____XXX,XX______,___XXXXX,X_______,
  __XXXXXX,X____XXX,XX______,___XXXXX,X_______,
  _XXXXXXX,X_____XX,XXX_____,___XXXXX,X_______,
  _XXXXXXX,X_____XX,XXX_____,___XXXXX,________,
  _XXXXXXX,X_____XX,XXX_____,__XXXXXX,________,
  _XXXXXXX,X______X,XXXX____,__XXXXX_,________,
  _XXX_XXX,X______X,XXXX____,__XXXXX_,________,
  _XXX_XXX,X______X,XXXX____,__XXXXX_,________,
  __X__XXX,X_______,XXXXX___,_XXXXX__,________,
  _____XXX,X_______,XXXXX___,_XXXXX__,________,
  _____XXX,X_______,XXXXX___,_XXXXX__,________,
  _____XXX,X_______,XXXXXX__,XXXXX___,________,
  _____XXX,X_______,_XXXXX__,XXXXX___,________,
  _____XXX,X_______,_XX_____,XXXXX___,________,
  _____XXX,X_______,_______X,XXXX____,________,
  _____XXX,X_______,_______X,XXXX____,________,
  _____XXX,X__XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XXX,X__XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XXX,X__XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XXX,X__XXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _____XXX,X_______,________,________,________,
  _____XXX,X_______,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_505C[175] = { /* code 505C */
  ______XX,X_______,_____XXX,X_______,________,
  ______XX,XXX_____,___XXXXX,X_______,________,
  ______XX,XX______,____XXXX,X_______,________,
  ______XX,XX_XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,XX_XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,X__XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,X__XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ____XXXX,X_______,________,________,________,
  ____XXXX,_____XXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,_____XXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,_____XXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,_____XXX,X_______,____XXXX,________,
  __XXXXXX,_____XXX,X_______,____XXXX,________,
  __XXXXXX,_____XXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,_____XXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,_____XXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,________,________,________,________,
  _XXXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XX_XXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XX_XXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ____XXXX,_XXXXX__,________,_______X,XXX_____,
  ____XXXX,_XXXXX__,________,_______X,XXX_____,
  ____XXXX,________,________,________,________,
  ____XXXX,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,________,_____XXX,XX______,________,
  ____XXXX,________,_____XXX,XX______,________,
  ____XXXX,________,_____XXX,XX______,________,
  ____XXXX,_______X,XXXXXXXX,XX______,________,
  ____XXXX,________,XXXXXXXX,XX______,________,
  ____XXXX,________,XXXXXXXX,X_______,________,
  ____XXXX,________,XXXXXXXX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_590D[170] = { /* code 590D */
  ______XX,XXX_____,________,________,________,
  ______XX,XXX_____,________,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _XXXXXXX,X_______,________,____XXXX,________,
  _XXX_XXX,X_______,________,____XXXX,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _____XXX,X_______,________,____XXXX,________,
  _____XXX,X_______,________,____XXXX,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,XXXXX___,________,________,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXX___,________,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,_____XXX,XXXXXX__,________,
  _XXXXXX_,__XXXXXX,XXXXXXXX,XXXX____,________,
  __XXXX__,____XXXX,XXXXXXXX,XX______,________,
  ___X____,___XXXXX,XXXXXXXX,XX______,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,XXX_____,
  __XXXXXX,XXXXXXX_,______XX,XXXXXXXX,XX______,
  ___XXXXX,XXX_____,________,_XXXXXXX,XX______,
  ____XXX_,________,________,______XX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_59CB[170] = { /* code 59CB */
  _____XXX,XX______,______XX,________,________,
  _____XXX,XX______,_____XXX,XXX_____,________,
  _____XXX,X_______,_____XXX,XX______,________,
  _____XXX,X_______,____XXXX,XX______,________,
  _____XXX,X_______,___XXXXX,X____X__,________,
  ____XXXX,X_______,___XXXXX,__XXXXX_,________,
  ____XXXX,X_______,__XXXXX_,___XXXX_,________,
  _XXXXXXX,XXXXXXX_,__XXXXX_,___XXXXX,________,
  _XXXXXXX,XXXXXXX_,_XXXXX__,____XXXX,________,
  _XXXXXXX,XXXXXXX_,XXXXX___,____XXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXX__XX,XXXXXXXX,X_______,
  ___XXXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXX_,__XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXX_,__XXXXX_,XXXXXX__,_______X,XXX_____,
  ___XXXX_,__XXXX__,________,_______X,XXX_____,
  __XXXXX_,__XXXX__,________,_______X,X_______,
  __XXXXX_,__XXXX__,________,________,________,
  __XXXX__,_XXXXX__,XXXXXXXX,XXXXXXXX,XX______,
  __XXXX__,_XXXXX__,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,_XXXX___,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXX___,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXX___,XXXXX___,_____XXX,XX______,
  _____XXX,XXXX____,XXXXX___,_____XXX,XX______,
  ______XX,XXXXX___,XXXXX___,_____XXX,XX______,
  ______XX,XXXXXX__,XXXXX___,_____XXX,XX______,
  _____XXX,XXXXXXX_,XXXXX___,_____XXX,XX______,
  ____XXXX,XXXXXXXX,XXXXX___,_____XXX,XX______,
  ___XXXXX,XXXXXXX_,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,X__XXX__,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXXX,____X___,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXX_,________,XXXXXXXX,XXXXXXXX,XX______,
  __XXXX__,________,XXXXX___,_____XXX,XX______,
  ___X____,________,XXXXX___,_____XXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_5B9E[175] = { /* code 5B9E */
  ________,_______X,XXXX____,________,________,
  ________,______XX,XXXX____,________,________,
  ________,______XX,XXXX____,________,________,
  ________,_______X,XXXXX___,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXX__,________,________,____XXXX,X_______,
  _XXXXX__,_X______,__XXXXX_,____XXXX,X_______,
  _XXXXX__,XXXXX___,__XXXXX_,____XXXX,X_______,
  _XXXXX_X,XXXXXXX_,__XXXXX_,____XXXX,X_______,
  _XXXXX__,_XXXXXXX,X_XXXXX_,____XXXX,X_______,
  ________,__XXXXXX,__XXXXX_,________,________,
  ______X_,____XXX_,__XXXX__,________,________,
  _____XXX,XX____X_,__XXXX__,________,________,
  ____XXXX,XXX_____,_XXXXX__,________,________,
  ______XX,XXXXX___,_XXXXX__,________,________,
  _______X,XXXXX___,_XXXXX__,________,________,
  ________,_XXXX___,_XXXXX__,________,________,
  ________,__XX____,_XXXXX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_______X,XXXXX___,________,________,
  ________,______XX,XXXXXXX_,________,________,
  ________,____XXXX,XXXXXXXX,X_______,________,
  ________,_XXXXXXX,XXXXXXXX,XXXX____,________,
  _____XXX,XXXXXXXX,X__XXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,_____XXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXX_,________,XXXXXXXX,XX______,
  __XXXXXX,XXXXX___,________,__XXXXXX,X_______,
  ___XXXXX,XX______,________,_____XXX,X_______,
  ____XX__,________,________,_______X,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_5EA6[175] = { /* code 5EA6 */
  ________,________,__XXXX__,________,________,
  ________,________,XXXXXX__,________,________,
  ________,________,_XXXXXX_,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXX_,________,________,________,________,
  ___XXXX_,____XXXX,X_______,_XXXXX__,________,
  ___XXXX_,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXX_,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXX_,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXX_,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ___XXXX_,____XXXX,X_______,_XXXXX__,________,
  ___XXXX_,____XXXX,X_______,_XXXXX__,________,
  ___XXXX_,____XXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXX_,____XXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXX_,____XXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXX_,____XXXX,XXXXXXXX,XXXXXX__,________,
  ___XXXX_,________,________,________,________,
  ___XXXX_,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXX_,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXX_,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXX_,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXX_,___XXXXX,________,__XXXXX_,________,
  __XXXXX_,____XXXX,XX______,_XXXXX__,________,
  __XXXXX_,_____XXX,XXX____X,XXXXX___,________,
  __XXXXX_,______XX,XXXXX_XX,XXXX____,________,
  _XXXXX__,_______X,XXXXXXXX,XXX_____,________,
  _XXXXX__,________,XXXXXXXX,XXX_____,________,
  _XXXXX__,___XXXXX,XXXXXXXX,XXXXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _XXXX__X,XXXXXXXX,XXX____X,XXXXXXXX,XXX_____,
  __XXX___,XXXXXXX_,________,__XXXXXX,XX______,
  ___X____,XXX_____,________,______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_5F00[165] = { /* code 5F00 */
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  ________,XXXXX___,______XX,XXX_____,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,XXXXX___,______XX,XXX_____,________,
  _______X,XXXXX___,______XX,XXX_____,________,
  _______X,XXXXX___,______XX,XXX_____,________,
  _______X,XXXX____,______XX,XXX_____,________,
  _______X,XXXX____,______XX,XXX_____,________,
  ______XX,XXXX____,______XX,XXX_____,________,
  ______XX,XXXX____,______XX,XXX_____,________,
  _____XXX,XXX_____,______XX,XXX_____,________,
  ____XXXX,XXX_____,______XX,XXX_____,________,
  ___XXXXX,XX______,______XX,XXX_____,________,
  _XXXXXXX,XX______,______XX,XXX_____,________,
  XXXXXXXX,X_______,______XX,XXX_____,________,
  _XXXXXXX,________,______XX,XXX_____,________,
  __XXXXX_,________,______XX,XXX_____,________,
  ____X___,________,______XX,XXX_____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_65F6[170] = { /* code 65F6 */
  ________,________,________,_XXXXXX_,________,
  ________,________,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX_X,XXXXXXXX,XXXXXXXX,X_______,
  XXXXX___,_XXXXX_X,XXXXXXXX,XXXXXXXX,X_______,
  XXXXX___,_XXXXX_X,XXXXXXXX,XXXXXXXX,X_______,
  XXXXX___,_XXXXX_X,XXXXXXXX,XXXXXXXX,X_______,
  XXXXX___,_XXXXX_X,XXXXXXXX,XXXXXXXX,X_______,
  XXXXX___,_XXXXX__,________,_XXXXXX_,________,
  XXXXX___,_XXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,_XX_____,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,XXX_____,_XXXXXX_,________,
  XXXXXXXX,XXXXXX_X,XXXX____,_XXXXXX_,________,
  XXXXXXXX,XXXXXX_X,XXXXX___,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,XXXXXX__,_XXXXXX_,________,
  XXXXX___,_XXXXX__,_XXXXX__,_XXXXXX_,________,
  XXXXX___,_XXXXX__,_XXXXXX_,_XXXXXX_,________,
  XXXXX___,_XXXXX__,__XXXXXX,_XXXXXX_,________,
  XXXXX___,_XXXXX__,___XXXXX,XXXXXXX_,________,
  XXXXX___,_XXXXX__,___XXXX_,_XXXXXX_,________,
  XXXXX___,_XXXXX__,____X___,_XXXXXX_,________,
  XXXXX___,_XXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,________,_XXXXXX_,________,
  XXXXXXXX,XXXXXX__,__XXXXXX,XXXXXX__,________,
  XXXXX___,_XXXXX__,__XXXXXX,XXXXXX__,________,
  XXXXX___,_XXXXX__,__XXXXXX,XXXXXX__,________,
  ________,________,__XXXXXX,XXXXX___,________,
  ________,________,___XXXXX,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_671B[165] = { /* code 671B */
  _____XXX,________,________,________,________,
  ____XXXX,______XX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,X_____XX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXX_XX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXX_XX,XXX_____,____XXXX,________,
  XXXXXXXX,XXXXX_XX,XXX_____,____XXXX,________,
  XXXXXXXX,XXXXX_XX,XXXXXXXX,XXXXXXXX,________,
  __XXXXX_,______XX,XXXXXXXX,XXXXXXXX,________,
  __XXXXX_,______XX,XXX_____,____XXXX,________,
  __XXXXX_,___XX_XX,XXX_____,____XXXX,________,
  __XXXXX_,_XXXX_XX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXX_XX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,XXXXX_XX,XXX_____,____XXXX,________,
  __XXXXXX,XXXX_XXX,XXX_____,___XXXXX,________,
  _XXXXXXX,X____XXX,XX____XX,XXXXXXXX,________,
  __XXXXX_,_____XXX,XX____XX,XXXXXXXX,________,
  ___XX___,________,X______X,XXXXXX__,________,
  ________,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ________,_______X,XXXX____,________,________,
  ________,_______X,XXXX____,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,_______X,XXXX____,________,________,
  ________,_______X,XXXX____,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_671F[170] = { /* code 671F */
  __XXXXX_,____XXXX,________,________,________,
  __XXXXX_,____XXXX,___XXXXX,XXXXXXXX,X_______,
  __XXXXX_,____XXXX,___XXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX_XXXXX,____XXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX_XXXXX,____XXXX,X_______,
  __XXXXX_,____XXXX,___XXXXX,____XXXX,X_______,
  __XXXXX_,____XXXX,___XXXXX,____XXXX,X_______,
  __XXXXXX,XXXXXXXX,___XXXXX,____XXXX,X_______,
  __XXXXXX,XXXXXXXX,___XXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,___XXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,___XXXXX,XXXXXXXX,X_______,
  __XXXXX_,____XXXX,___XXXXX,XXXXXXXX,X_______,
  __XXXXX_,____XXXX,___XXXXX,____XXXX,X_______,
  __XXXXXX,XXXXXXXX,___XXXXX,____XXXX,X_______,
  __XXXXXX,XXXXXXXX,___XXXXX,____XXXX,X_______,
  __XXXXXX,XXXXXXXX,___XXXXX,____XXXX,X_______,
  __XXXXXX,XXXXXXXX,___XXXXX,____XXXX,X_______,
  __XXXXX_,____XXXX,___XXXXX,XXXXXXXX,X_______,
  __XXXXX_,____XXXX,___XXXXX,XXXXXXXX,X_______,
  __XXXXX_,____XXXX,___XXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX_XXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX_XXXXX,____XXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX_XXXX_,____XXXX,X_______,
  XXXXXXXX,XXXXXXXX,XX_XXXX_,____XXXX,X_______,
  ____XX__,____XX__,__XXXXX_,____XXXX,X_______,
  ___XXXX_,___XXXX_,__XXXXX_,____XXXX,X_______,
  __XXXXXX,__XXXXXX,__XXXXX_,____XXXX,X_______,
  _XXXXXX_,___XXXXX,XXXXXX__,XXXXXXXX,X_______,
  XXXXXX__,____XXXX,XXXXXX__,XXXXXXXX,X_______,
  XXXXXX__,_____XXX,XXXXXX__,XXXXXXXX,________,
  _XXXX___,______X_,__XXX___,_XXXXXX_,________,
  ___X____,________,____X___,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_6B62[165] = { /* code 6B62 */
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXXXX,XXXXXXXX,________,
  _____XXX,XX______,_XXXXXXX,XXXXXXXX,________,
  _____XXX,XX______,_XXXXXXX,XXXXXXXX,________,
  _____XXX,XX______,_XXXXXXX,XXXXXXXX,________,
  _____XXX,XX______,_XXXXXXX,XXXXXXXX,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  _____XXX,XX______,_XXXXX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_6C14[170] = { /* code 6C14 */
  _______X,XXXX____,________,________,________,
  ______XX,XXXX____,________,________,________,
  ______XX,XXXX____,________,________,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,X_______,________,________,________,
  _XXXXXXX,________,________,________,________,
  _XXXXXX_,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXX__,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXX___,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXX___,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ___X____,________,________,________,________,
  ________,________,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ________,________,________,XXXXX___,________,
  ________,________,________,XXXXX___,________,
  ________,________,________,XXXXX___,________,
  ________,________,________,XXXXX___,________,
  ________,________,________,XXXXX___,X_______,
  ________,________,________,XXXXX___,XXX_____,
  ________,________,________,XXXXX___,XXX_____,
  ________,________,________,_XXXX___,XXX_____,
  ________,________,________,_XXXXX__,XXX_____,
  ________,________,________,_XXXXX__,XXX_____,
  ________,________,________,_XXXXXXX,XXX_____,
  ________,________,________,__XXXXXX,XXX_____,
  ________,________,________,__XXXXXX,XX______,
  ________,________,________,___XXXXX,XX______,
  ________,________,________,____XXXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_6C27[170] = { /* code 6C27 */
  _____XXX,XX______,________,________,________,
  ____XXXX,X_______,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXX__,________,________,________,________,
  _XXXX_XX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXX_XX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __XX__XX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  __X_____,________,________,________,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  _______X,X_______,XXX_____,_XXXXX__,________,
  _____XXX,XX_____X,XXXX____,_XXXXX__,________,
  ______XX,XXX___XX,XXXX____,_XXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,_XXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,_XXXXX__,________,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,_XXXXX__,________,
  ________,__XXXXX_,________,_XXXXX__,________,
  ________,__XXXXX_,________,_XXXXX__,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,_XXXXX__,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,_XXXXX__,________,
  __XXXXXX,XXXXXXXX,XXXXXXX_,_XXXXX__,XX______,
  ________,__XXXXX_,________,_XXXXX__,XXX_____,
  ________,__XXXXX_,________,_XXXXX__,XXX_____,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX_X,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_XXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,X_XXXXXX,XX______,
  ________,__XXXXX_,________,__XXXXXX,XX______,
  ________,__XXXXX_,________,___XXXXX,X_______,
  ________,__XXXXX_,________,___XXXXX,X_______,
  ________,__XXXXX_,________,_____XXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_6D53[170] = { /* code 6D53 */
  ___XX___,________,____XXXX,________,________,
  __XXXXX_,________,____XXXX,X_______,________,
  _XXXXXXX,________,____XXXX,X_______,________,
  __XXXXXX,XX______,____XXXX,X_______,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _____XXX,X_XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ______X_,__XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ________,__XXXX__,__XXXXX_,______XX,XXX_____,
  ___X____,__XXXX__,_XXXXXXX,______XX,XXX_____,
  __XXXX__,__XXXX__,_XXXXXXX,______XX,XXX_____,
  _XXXXXXX,________,XXXXXXXX,________,________,
  _XXXXXXX,X_______,XXXXXXXX,_______X,________,
  ___XXXXX,_______X,XXXXXXXX,X_____XX,X_______,
  ____XXX_,_______X,XXXX_XXX,X____XXX,XX______,
  _____X__,______XX,XXX__XXX,XX__XXXX,XXX_____,
  ________,_____XXX,XXX___XX,XX_XXXXX,XX______,
  ____X___,____XXXX,XXX___XX,XXXXXXXX,________,
  ____XXXX,___XXXXX,XXX___XX,XXXXXXX_,________,
  ___XXXXX,__XXXXXX,XXX____X,XXXXX___,________,
  ___XXXXX,_XXXXXXX,XXX____X,XXXX____,________,
  ___XXXXX,XXXXXXXX,XXX____X,XXXXX___,________,
  ___XXXXX,XXXXXXXX,XXX_____,XXXXXX__,________,
  ___XXXXX,XXXXX_XX,XXX_____,XXXXXXX_,________,
  ___XXXX_,XXXX__XX,XXX_____,_XXXXXXX,________,
  __XXXXX_,XXX___XX,XXX_____,X_XXXXXX,X_______,
  __XXXXX_,_X____XX,XXX__XXX,X_XXXXXX,XX______,
  __XXXXX_,______XX,XXXXXXXX,X__XXXXX,XXX_____,
  __XXXX__,______XX,XXXXXXXX,X___XXXX,XXX_____,
  __XXXX__,______XX,XXXXXXXX,X____XXX,XX______,
  _XXXXX__,______XX,XXXXXXX_,______XX,X_______,
  _XXXXX__,_____XXX,XXXXX___,_______X,________,
  _XXXXX__,______XX,XX______,________,________,
  ____XX__,_______X,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_6E29[170] = { /* code 6E29 */
  ____X___,________,________,________,________,
  ___XXX__,____XXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,____XXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,X___XXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,XX__XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,X___XXXX,________,____XXXX,________,
  _____XXX,____XXXX,________,____XXXX,________,
  ______X_,____XXXX,XXXXXXXX,XXXXXXXX,________,
  ________,____XXXX,XXXXXXXX,XXXXXXXX,________,
  ___X____,____XXXX,XXXXXXXX,XXXXXXXX,________,
  __XXX___,____XXXX,________,____XXXX,________,
  _XXXXXX_,____XXXX,________,____XXXX,________,
  _XXXXXXX,____XXXX,XXXXXXXX,XXXXXXXX,________,
  __XXXXXX,X___XXXX,XXXXXXXX,XXXXXXXX,________,
  ___XXXXX,____XXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXX_,____XXXX,XXXXXXXX,XXXXXXXX,________,
  _____X__,________,________,________,________,
  ________,________,________,________,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____X___,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ___XXXXX,__XXXXX_,_XXXX__X,XXX__XXX,XX______,
  ___XXXXX,__XXXXX_,_XXXX__X,XXX__XXX,XX______,
  ___XXXXX,__XXXXX_,_XXXX__X,XXX__XXX,XX______,
  ___XXXX_,__XXXXX_,_XXXX__X,XXX__XXX,XX______,
  __XXXXX_,__XXXXX_,_XXXX__X,XXX__XXX,XX______,
  __XXXXX_,__XXXXX_,_XXXX__X,XXX__XXX,XX______,
  __XXXXX_,__XXXXX_,_XXXX__X,XXX__XXX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  _XXXXX_X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  ____XX__,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_8BA1[170] = { /* code 8BA1 */
  _____X__,________,____XXXX,X_______,________,
  ___XXXX_,________,____XXXX,X_______,________,
  __XXXXXX,________,____XXXX,X_______,________,
  __XXXXXX,________,____XXXX,X_______,________,
  ___XXXXX,X_______,____XXXX,X_______,________,
  ____XXXX,XX______,____XXXX,X_______,________,
  ____XXXX,XX______,____XXXX,X_______,________,
  _____XXX,________,____XXXX,X_______,________,
  ______X_,________,____XXXX,X_______,________,
  ________,________,____XXXX,X_______,________,
  ________,________,____XXXX,X_______,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,___XXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,________,____XXXX,X_______,________,
  ___XXXXX,________,____XXXX,X_______,________,
  ___XXXXX,________,____XXXX,X_______,________,
  ___XXXXX,________,____XXXX,X_______,________,
  ___XXXXX,________,____XXXX,X_______,________,
  ___XXXXX,________,____XXXX,X_______,________,
  ___XXXXX,____X___,____XXXX,X_______,________,
  ___XXXXX,___XX___,____XXXX,X_______,________,
  ___XXXXX,_XXXX___,____XXXX,X_______,________,
  ___XXXXX,XXXXX___,____XXXX,X_______,________,
  ___XXXXX,XXXXX___,____XXXX,X_______,________,
  ___XXXXX,XXXXX___,____XXXX,X_______,________,
  ___XXXXX,XXX_____,____XXXX,X_______,________,
  ___XXXXX,XX______,____XXXX,X_______,________,
  ___XXXXX,________,____XXXX,X_______,________,
  ____XXX_,________,____XXXX,X_______,________,
  ____XX__,________,____XXXX,X_______,________,
  ________,________,____XXXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont47_9645[165] = { /* code 9645 */
  XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXX_XXX,XXXXXXXX,XXXXXXXX,________,
  XXXX___X,XXX_____,________,________,________,
  XXXX___X,XXX_____,________,________,________,
  XXXX__XX,XXX_____,________,________,________,
  XXXX__XX,XX______,________,________,________,
  XXXX__XX,XX______,________,________,________,
  XXXX__XX,XX__XXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXX_XXX,X___XXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXX_XXX,X___XXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXX_XXX,X___XXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,X_______,____XXXX,X_______,________,
  XXXX_XXX,XX______,____XXXX,X_______,________,
  XXXX__XX,XX______,____XXXX,X_______,________,
  XXXX__XX,XXX____X,____XXXX,X___XX__,________,
  XXXX___X,XXX___XX,XXX_XXXX,X_XXXX__,________,
  XXXX___X,XXX___XX,XX__XXXX,X_XXXXX_,________,
  XXXX___X,XXX___XX,XX__XXXX,X_XXXXX_,________,
  XXXX____,XXXX_XXX,XX__XXXX,X__XXXX_,________,
  XXXX____,XXXX_XXX,X___XXXX,X__XXXXX,________,
  XXXX___X,XXXXXXXX,X___XXXX,X__XXXXX,________,
  XXXXXXXX,XXXXXXXX,X___XXXX,X___XXXX,X_______,
  XXXX_XXX,XXX_XXXX,____XXXX,X___XXXX,X_______,
  XXXX_XXX,XXXXXXXX,____XXXX,X____XXX,X_______,
  XXXX_XXX,XX_XXXXX,____XXXX,X____XXX,XX______,
  XXXX_XXX,__XXXXX_,____XXXX,X____XXX,XX______,
  XXXX____,_____XX_,____XXXX,X____XX_,________,
  XXXX____,_______X,XXXXXXXX,X_______,________,
  XXXX____,_______X,XXXXXXXX,X_______,________,
  XXXX____,________,XXXXXXXX,________,________,
  XXXX____,________,XXXXXXX_,________,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont47_CharInfo[32] = {
   {  18,  18,   5,  18,  27, acGUI_FontFont47_002B } /* code 002B, PLUS SIGN */
  ,{  10,   4,   3,  26,  16, acGUI_FontFont47_002D } /* code 002D, HYPHEN-MINUS */
  ,{   7,   6,   2,  32,  10, acGUI_FontFont47_002E } /* code 002E, FULL STOP */
  ,{  20,  28,   1,  10,  22, acGUI_FontFont47_0030 } /* code 0030, DIGIT ZERO */
  ,{  12,  28,   3,  10,  22, acGUI_FontFont47_0031 } /* code 0031, DIGIT ONE */
  ,{  18,  28,   2,  10,  22, acGUI_FontFont47_0032 } /* code 0032, DIGIT TWO */
  ,{  17,  28,   3,  10,  22, acGUI_FontFont47_0033 } /* code 0033, DIGIT THREE */
  ,{  21,  28,   1,  10,  22, acGUI_FontFont47_0034 } /* code 0034, DIGIT FOUR */
  ,{  17,  28,   3,  10,  22, acGUI_FontFont47_0035 } /* code 0035, DIGIT FIVE */
  ,{  19,  28,   2,  10,  22, acGUI_FontFont47_0036 } /* code 0036, DIGIT SIX */
  ,{  19,  28,   1,  10,  22, acGUI_FontFont47_0037 } /* code 0037, DIGIT SEVEN */
  ,{  18,  28,   2,  10,  22, acGUI_FontFont47_0038 } /* code 0038, DIGIT EIGHT */
  ,{  19,  28,   2,  10,  22, acGUI_FontFont47_0039 } /* code 0039, DIGIT NINE */
  ,{   7,  20,   2,  18,  10, acGUI_FontFont47_003A } /* code 003A, COLON */
  ,{  15,  20,   2,  18,  18, acGUI_FontFont47_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{  36,  34,   0,   9,  36, acGUI_FontFont47_4F4D } /* code 4F4D */
  ,{  35,  35,   0,   8,  36, acGUI_FontFont47_505C } /* code 505C */
  ,{  35,  34,   0,   9,  36, acGUI_FontFont47_590D } /* code 590D */
  ,{  36,  34,   0,   9,  36, acGUI_FontFont47_59CB } /* code 59CB */
  ,{  34,  35,   1,   8,  36, acGUI_FontFont47_5B9E } /* code 5B9E */
  ,{  35,  35,   0,   8,  36, acGUI_FontFont47_5EA6 } /* code 5EA6 */
  ,{  34,  33,   1,  10,  36, acGUI_FontFont47_5F00 } /* code 5F00 */
  ,{  33,  34,   2,   9,  36, acGUI_FontFont47_65F6 } /* code 65F6 */
  ,{  34,  33,   1,   9,  36, acGUI_FontFont47_671B } /* code 671B */
  ,{  33,  34,   1,   9,  36, acGUI_FontFont47_671F } /* code 671F */
  ,{  34,  33,   1,   9,  36, acGUI_FontFont47_6B62 } /* code 6B62 */
  ,{  36,  34,   0,   9,  36, acGUI_FontFont47_6C14 } /* code 6C14 */
  ,{  35,  34,   1,   8,  36, acGUI_FontFont47_6C27 } /* code 6C27 */
  ,{  36,  34,   0,   9,  36, acGUI_FontFont47_6D53 } /* code 6D53 */
  ,{  36,  34,   0,   9,  36, acGUI_FontFont47_6E29 } /* code 6E29 */
  ,{  34,  34,   1,   9,  36, acGUI_FontFont47_8BA1 } /* code 8BA1 */
  ,{  34,  33,   2,  10,  36, acGUI_FontFont47_9645 } /* code 9645 */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop21 = {
   0x9645 /* first character */
  ,0x9645 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 31] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop20 = {
   0x8BA1 /* first character */
  ,0x8BA1 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 30] /* address of first character */
  ,&GUI_FontFont47_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop19 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 29] /* address of first character */
  ,&GUI_FontFont47_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop18 = {
   0x6D53 /* first character */
  ,0x6D53 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 28] /* address of first character */
  ,&GUI_FontFont47_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop17 = {
   0x6C27 /* first character */
  ,0x6C27 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 27] /* address of first character */
  ,&GUI_FontFont47_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop16 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 26] /* address of first character */
  ,&GUI_FontFont47_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop15 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 25] /* address of first character */
  ,&GUI_FontFont47_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop14 = {
   0x671F /* first character */
  ,0x671F /* last character  */
  ,&GUI_FontFont47_CharInfo[ 24] /* address of first character */
  ,&GUI_FontFont47_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop13 = {
   0x671B /* first character */
  ,0x671B /* last character  */
  ,&GUI_FontFont47_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFont47_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop12 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFont47_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop11 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFont47_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop10 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFont47_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop9 = {
   0x5B9E /* first character */
  ,0x5B9E /* last character  */
  ,&GUI_FontFont47_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFont47_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop8 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontFont47_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFont47_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop7 = {
   0x590D /* first character */
  ,0x590D /* last character  */
  ,&GUI_FontFont47_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFont47_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop6 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFont47_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFont47_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop5 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontFont47_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFont47_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop4 = {
   0x0073 /* first character */
  ,0x0073 /* last character  */
  ,&GUI_FontFont47_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFont47_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop3 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontFont47_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont47_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop2 = {
   0x002D /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontFont47_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont47_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont47_Prop1 = {
   0x002B /* first character */
  ,0x002B /* last character  */
  ,&GUI_FontFont47_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont47_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_Font47 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,47 /* height of font  */
  ,47 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont47_Prop1}
  ,38 /* Baseline */
  ,20 /* Height of lowercase characters */
  ,28 /* Height of capital characters */
};

