/*********************************************************************
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                           www.segger.com                           *
**********************************************************************
*                                                                    *
* C-file generated by                                                *
*                                                                    *
*        emWin Font Converter (ST) version 5.44                      *
*        Compiled Nov 10 2017, 08:53:23                              *
*                                                                    *
*        (c) 1998 - 2017 Segger Microcontroller GmbH & Co. KG        *
*                                                                    *
**********************************************************************
*                                                                    *
* Source file: Font45.c                                              *
* Font:        ºÚÌå                                                  *
* Height:      45                                                    *
*                                                                    *
**********************************************************************
*                                                                    *
* Initial font height:  45                                           *
* Range disabled:       0000 - FFFF                                  *
* Read pattern file: C:\Users\ChxxxXL\Downloads\en.stm32cubef4_v1-26-0\STM32Cube_FW_F4_V1.26.0\Middlewares\ST\STemWin\Software\Font.txt*
*                                                                    *
**********************************************************************
*/

#include "GUI.h"

#ifndef GUI_CONST_STORAGE
  #define GUI_CONST_STORAGE const
#endif

/* The following line needs to be included in any file selecting the
   font.
*/
extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont45;

/* Start of unicode area <Basic Latin> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont45_002B[ 60] = { /* code 002B, PLUS SIGN */
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________,
  ________,XXXX____,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_002D[  9] = { /* code 002D, HYPHEN-MINUS */
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___,
  XXXXXXXX,XXXXXXXX,XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_002E[  4] = { /* code 002E, FULL STOP */
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0030[ 93] = { /* code 0030, DIGIT ZERO */
  ______XX,XXXXXXX_,________,
  _____XXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,X___XXXX,XX______,
  ___XXXXX,_____XXX,XX______,
  __XXXXX_,______XX,XXX_____,
  __XXXXX_,_______X,XXX_____,
  _XXXXX__,_______X,XXX_____,
  _XXXXX__,_______X,XXXX____,
  _XXXXX__,_______X,XXXX____,
  _XXXX___,_______X,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXX___,________,XXXX____,
  _XXXXX__,_______X,XXXX____,
  _XXXXX__,_______X,XXXX____,
  _XXXXX__,_______X,XXX_____,
  __XXXXX_,______XX,XXX_____,
  __XXXXX_,______XX,XXX_____,
  ___XXXXX,_____XXX,XX______,
  ___XXXXX,X___XXXX,XX______,
  ____XXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,________,
  _______X,XXXXXXX_,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0031[ 60] = { /* code 0031, DIGIT ONE */
  _______X,XX______,
  ______XX,XX______,
  _____XXX,XX______,
  ____XXXX,XX______,
  ___XXXXX,XX______,
  __XXXXXX,XX______,
  XXXXXXXX,XX______,
  XXXXX_XX,XX______,
  XXX___XX,XX______,
  XX____XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______,
  ______XX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0032[ 93] = { /* code 0032, DIGIT TWO */
  ________,__XX____,________,
  ______XX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  __XXXXXX,X____XXX,XXX_____,
  __XXXXX_,______XX,XXX_____,
  _XXXXX__,______XX,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  ________,_______X,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,_____XXX,XX______,
  ________,_____XXX,XX______,
  ________,____XXXX,X_______,
  ________,___XXXXX,________,
  ________,__XXXXXX,________,
  ________,__XXXXX_,________,
  ________,_XXXXX__,________,
  ________,XXXXX___,________,
  _______X,XXXXX___,________,
  ______XX,XXXX____,________,
  ______XX,XXX_____,________,
  _____XXX,XX______,________,
  ____XXXX,X_______,________,
  ___XXXXX,________,________,
  __XXXXX_,________,________,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXX____,
  _XXXXXXX,XXXXXXXX,XXXX____};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0033[ 93] = { /* code 0033, DIGIT THREE */
  ________,________,________,
  _____XXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,X_______,
  __XXXXX_,____XXXX,XX______,
  _XXXXX__,_____XXX,XX______,
  _XXXX___,______XX,XX______,
  XXXXX___,______XX,XX______,
  XXXX____,______XX,XX______,
  ________,______XX,XX______,
  ________,_____XXX,XX______,
  ________,_____XXX,XX______,
  ________,____XXXX,X_______,
  ________,__XXXXXX,________,
  _______X,XXXXXXX_,________,
  _______X,XXXXXXX_,________,
  ________,XXXXXXXX,________,
  ________,___XXXXX,X_______,
  ________,_____XXX,XX______,
  ________,_____XXX,XX______,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  ________,______XX,XXX_____,
  XXXX____,______XX,XXX_____,
  XXXXX___,______XX,XXX_____,
  XXXXX___,_____XXX,XX______,
  _XXXXX__,_____XXX,XX______,
  _XXXXXX_,___XXXXX,X_______,
  __XXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,________,
  _____XXX,XXXXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0034[ 90] = { /* code 0034, DIGIT FOUR */
  ________,_____XXX,X_______,
  ________,_____XXX,X_______,
  ________,____XXXX,X_______,
  ________,___XXXXX,X_______,
  ________,__XXXXXX,X_______,
  ________,__XXXXXX,X_______,
  ________,_XXXXXXX,X_______,
  ________,XXXXXXXX,X_______,
  ________,XXXXXXXX,X_______,
  _______X,XXXX_XXX,X_______,
  ______XX,XXX__XXX,X_______,
  ______XX,XX___XXX,X_______,
  _____XXX,XX___XXX,X_______,
  ____XXXX,X____XXX,X_______,
  ____XXXX,_____XXX,X_______,
  ___XXXXX,_____XXX,X_______,
  __XXXXX_,_____XXX,X_______,
  _XXXXX__,_____XXX,X_______,
  _XXXX___,_____XXX,X_______,
  XXXXX___,_____XXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,_____XXX,X_______,
  ________,_____XXX,X_______,
  ________,_____XXX,X_______,
  ________,_____XXX,X_______,
  ________,_____XXX,X_______,
  ________,_____XXX,X_______,
  ________,_____XXX,X_______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0035[ 93] = { /* code 0035, DIGIT FIVE */
  ____XXXX,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXX_____,
  ___XXXXX,________,________,
  ___XXXX_,________,________,
  ___XXXX_,________,________,
  ___XXXX_,________,________,
  __XXXXX_,________,________,
  __XXXX__,________,________,
  __XXXX__,________,________,
  __XXXXXX,XXXXXX__,________,
  _XXXXXXX,XXXXXXXX,________,
  _XXXXXXX,XXXXXXXX,X_______,
  _XXXXXX_,____XXXX,XX______,
  _XXXXX__,_____XXX,XXX_____,
  __XXX___,______XX,XXX_____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  ________,_______X,XXXX____,
  XXXX____,_______X,XXXX____,
  XXXX____,______XX,XXX_____,
  XXXXX___,______XX,XXX_____,
  _XXXXX__,_____XXX,XXX_____,
  _XXXXXX_,____XXXX,XX______,
  __XXXXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,________,
  _____XXX,XXXXXX__,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0036[ 93] = { /* code 0036, DIGIT SIX */
  ________,__XXXXX_,________,
  ________,_XXXXX__,________,
  ________,_XXXXX__,________,
  ________,XXXXX___,________,
  _______X,XXXX____,________,
  _______X,XXXX____,________,
  ______XX,XXX_____,________,
  _____XXX,XX______,________,
  _____XXX,XX______,________,
  ____XXXX,X_______,________,
  ___XXXXX,________,________,
  ___XXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,XX______,
  _XXXXXX_,_____XXX,XXX_____,
  _XXXXX__,______XX,XXX_____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,________,XXXX____,
  XXXX____,________,XXXX____,
  XXXX____,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  _XXXXX__,______XX,XXX_____,
  _XXXXXXX,_____XXX,XXX_____,
  __XXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXX_,________,
  ________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0037[ 90] = { /* code 0037, DIGIT SEVEN */
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  XXXXXXXX,XXXXXXXX,XXXX____,
  ________,_______X,XXXX____,
  ________,______XX,XXX_____,
  ________,______XX,XX______,
  ________,_____XXX,XX______,
  ________,_____XXX,X_______,
  ________,____XXXX,X_______,
  ________,____XXXX,________,
  ________,___XXXXX,________,
  ________,___XXXX_,________,
  ________,__XXXXX_,________,
  ________,__XXXX__,________,
  ________,_XXXXX__,________,
  ________,_XXXX___,________,
  ________,XXXXX___,________,
  ________,XXXXX___,________,
  ________,XXXX____,________,
  _______X,XXXX____,________,
  _______X,XXX_____,________,
  ______XX,XXX_____,________,
  ______XX,XXX_____,________,
  ______XX,XX______,________,
  _____XXX,XX______,________,
  _____XXX,XX______,________,
  _____XXX,XX______,________,
  _____XXX,X_______,________,
  ____XXXX,X_______,________,
  ____XXXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0038[ 90] = { /* code 0038, DIGIT EIGHT */
  _____XXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXXXXX,XX______,
  __XXXXXX,_____XXX,XX______,
  __XXXX__,______XX,XXX_____,
  _XXXXX__,______XX,XXX_____,
  _XXXXX__,_______X,XXX_____,
  _XXXX___,_______X,XXX_____,
  _XXXXX__,_______X,XXX_____,
  _XXXXX__,______XX,XXX_____,
  __XXXX__,______XX,XXX_____,
  __XXXXX_,_____XXX,XX______,
  ___XXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XX______,
  __XXXXXX,____XXXX,XXX_____,
  _XXXXXX_,______XX,XXX_____,
  _XXXXX__,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,________,XXXX____,
  XXXXX___,________,XXXX____,
  XXXXX___,________,XXXX____,
  XXXXX___,_______X,XXXX____,
  _XXXX___,_______X,XXXX____,
  _XXXXX__,______XX,XXX_____,
  _XXXXXX_,_____XXX,XXX_____,
  __XXXXXX,XXXXXXXX,XX______,
  ___XXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0039[ 90] = { /* code 0039, DIGIT NINE */
  _____XXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXXXX,XX______,
  __XXXXXX,____XXXX,XX______,
  _XXXXXX_,_____XXX,XXX_____,
  _XXXXX__,______XX,XXX_____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,_______X,XXXX____,
  XXXXX___,______XX,XXX_____,
  XXXXXX__,______XX,XXX_____,
  _XXXXXX_,_____XXX,XX______,
  _XXXXXXX,___XXXXX,XX______,
  __XXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,X_______,
  ______XX,XXXXXXXX,________,
  ________,___XXXXX,________,
  ________,__XXXXX_,________,
  ________,__XXXXX_,________,
  ________,_XXXXX__,________,
  ________,_XXXXX__,________,
  ________,XXXXX___,________,
  _______X,XXXX____,________,
  _______X,XXXX____,________,
  ______XX,XXX_____,________,
  ______XX,XXX_____,________,
  _____XXX,XX______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_003A[ 20] = { /* code 003A, COLON */
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  ________,
  XXXXX___,
  XXXXX___,
  XXXXX___,
  XXXXX___};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_0073[ 60] = { /* code 0073, LATIN SMALL LETTER S */
  _____XXX,XXXX____,________,
  ___XXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXXXX,________,
  _XXXXXX_,___XXXXX,________,
  XXXXX___,____XXXX,X_______,
  XXXXX___,____XXXX,X_______,
  XXXXX___,________,________,
  _XXXXX__,________,________,
  _XXXXXXX,________,________,
  __XXXXXX,XXXXX___,________,
  ___XXXXX,XXXXXXX_,________,
  _______X,XXXXXXXX,________,
  ________,___XXXXX,X_______,
  ________,____XXXX,X_______,
  XXXX____,_____XXX,X_______,
  XXXXX___,_____XXX,X_______,
  XXXXX___,____XXXX,X_______,
  _XXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,________,
  ___XXXXX,XXXXXX__,________};

/* Start of unicode area <CJK Unified Ideographs> */
GUI_CONST_STORAGE unsigned char acGUI_FontFont45_4E50[205] = { /* code 4E50 */
  ________,________,________,_______X,X_______,
  ________,________,________,__XXXXXX,X_______,
  ________,________,___XXXXX,XXXXXXXX,XX______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXX___,________,________,
  ____XXXX,X_______,________,________,________,
  ____XXXX,X_______,________,________,________,
  ____XXXX,X_______,__XXXXX_,________,________,
  ____XXXX,________,__XXXXX_,________,________,
  ____XXXX,________,__XXXXX_,________,________,
  ___XXXXX,________,__XXXXX_,________,________,
  ___XXXXX,________,__XXXX__,________,________,
  ___XXXXX,________,__XXXX__,________,________,
  ___XXXXX,________,__XXXX__,________,________,
  ___XXXXX,________,__XXXX__,________,________,
  __XXXXX_,________,__XXXX__,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXX__,________,__XXXX__,________,________,
  ________,________,__XXXX__,________,________,
  ________,________,__XXXX__,________,________,
  ________,_XXX____,__XXXX__,________,________,
  ________,XXXXX___,__XXXX__,___XXX__,________,
  ________,XXXXXX__,__XXXX__,__XXXXX_,________,
  _______X,XXXXX___,__XXXX__,__XXXXXX,________,
  ______XX,XXXX____,__XXXX__,___XXXXX,X_______,
  _____XXX,XXX_____,__XXXX__,____XXXX,XX______,
  ____XXXX,XX______,__XXXX__,_____XXX,XXX_____,
  ___XXXXX,X_______,__XXXX__,______XX,XXXX____,
  __XXXXXX,________,__XXXX__,_______X,XXXXX___,
  _XXXXXX_,________,__XXXX__,_______X,XXXXXX__,
  XXXXXX__,________,__XXXX__,________,XXXXXXX_,
  XXXXX___,________,__XXXX__,________,_XXXX___,
  _XXX____,________,__XXXX__,________,__XX____,
  ________,________,XXXXXX__,________,________,
  ________,____XXXX,XXXXXX__,________,________,
  ________,____XXXX,XXXXXX__,________,________,
  ________,____XXXX,XXXX____,________,________,
  ________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_4F4D[252] = { /* code 4F4D */
  ________,________,________,________,________,________,
  ________,_XXXX___,________,XXXX____,________,________,
  ________,_XXXXXX_,_______X,XXXX____,________,________,
  ________,_XXXXX__,________,XXXXX___,________,________,
  ________,XXXXXX__,________,XXXXXX__,________,________,
  ________,XXXXX___,________,_XXXXX__,________,________,
  ________,XXXXX___,________,_XXXXXX_,________,________,
  _______X,XXXX____,________,__XXX___,________,________,
  _______X,XXXX____,________,________,________,________,
  _______X,XXXX___X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,XXX____X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,XXX____X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _____XXX,XXX_____,________,________,________,________,
  _____XXX,XXX_____,________,________,________,________,
  ____XXXX,XXX_____,________,________,________,________,
  ____XXXX,XXX_____,________,________,XXXXX___,________,
  ___XXXXX,XXX_____,__XXXX__,________,XXXXX___,________,
  __XXXXXX,XXX_____,_XXXXX__,________,XXXXX___,________,
  __XXXXXX,XXX_____,__XXXX__,_______X,XXXXX___,________,
  _XXXXX_X,XXX_____,__XXXXX_,_______X,XXXX____,________,
  _XXXXX_X,XXX_____,__XXXXX_,_______X,XXXX____,________,
  __XXX__X,XXX_____,___XXXX_,_______X,XXXX____,________,
  __XX___X,XXX_____,___XXXXX,_______X,XXX_____,________,
  _______X,XXX_____,___XXXXX,______XX,XXX_____,________,
  _______X,XXX_____,____XXXX,______XX,XXX_____,________,
  _______X,XXX_____,____XXXX,X_____XX,XXX_____,________,
  _______X,XXX_____,____XXXX,X_____XX,XX______,________,
  _______X,XXX_____,____XXXX,X_____XX,XX______,________,
  _______X,XXX_____,_____XXX,XX___XXX,XX______,________,
  _______X,XXX_____,_____XXX,XX___XXX,XX______,________,
  _______X,XXX_____,_____XXX,XX___XXX,X_______,________,
  _______X,XXX_____,_____XXX,XX___XXX,X_______,________,
  _______X,XXX_____,______XX,X___XXXX,X_______,________,
  _______X,XXX_____,________,____XXXX,X_______,________,
  _______X,XXX_____,________,____XXXX,________,________,
  _______X,XXX__XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _______X,XXX__XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _______X,XXX__XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _______X,XXX_____,________,________,________,________,
  _______X,XXXX____,________,________,________,________,
  _______X,XXXX____,________,________,________,________,
  _______X,XXXX____,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_505C[246] = { /* code 505C */
  ________,XXX_____,________,__XXX___,________,________,
  ________,XXXXX___,________,_XXXXX__,________,________,
  ________,XXXXX___,________,_XXXXX__,________,________,
  ________,XXXX____,________,__XXXX__,________,________,
  _______X,XXXX__XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _______X,XXXX__XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _______X,XXX___XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ______XX,XXX_____,________,________,________,________,
  ______XX,XXX_____,________,________,________,________,
  _____XXX,XXX_____,________,________,________,________,
  _____XXX,XXX_____,_XXXXXXX,XXXXXXXX,XXXXXX__,________,
  ____XXXX,XXX_____,_XXXXXXX,XXXXXXXX,XXXXXX__,________,
  ____XXXX,XXX_____,_XXXX___,________,__XXXX__,________,
  ___XXXXX,XXX_____,_XXXX___,________,__XXXX__,________,
  ___XXXXX,XXX_____,_XXXX___,________,__XXXX__,________,
  __XXXXXX,XXX_____,_XXXX___,________,__XXXX__,________,
  __XXXXXX,XXX_____,_XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXXX_X,XXX_____,_XXXXXXX,XXXXXXXX,XXXXXX__,________,
  _XXXX__X,XXX_____,________,________,________,________,
  __XXX__X,XXX_____,________,________,________,________,
  _______X,XXX_XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _______X,XXX_XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _______X,XXX_XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,
  _______X,XXX_XXXX,________,________,_______X,XXX_____,
  _______X,XXX_XXXX,________,________,_______X,XXX_____,
  _______X,XXX_XXXX,________,________,_______X,XXX_____,
  _______X,XXX_____,_XXX____,________,____XXX_,________,
  _______X,XXX_____,_XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _______X,XXX_____,_XXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,_____XXX,XXXXXX__,________,________,
  _______X,XXX_____,______XX,XXXXXX__,________,________,
  _______X,XXX_____,______XX,XXXXXX__,________,________,
  _______X,XXX_____,______XX,XXXX____,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_590D[252] = { /* code 590D */
  ________,________,________,________,________,________,
  ________,___XXXX_,________,________,________,________,
  ________,___XXXXX,________,________,________,________,
  ________,__XXXXX_,________,________,________,________,
  ________,_XXXXX__,________,________,________,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _______X,XXXX____,________,________,________,________,
  ______XX,XXX_____,________,________,________,________,
  ____XXXX,XX______,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _XXXXXX_,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  __XXXX__,XXXXX___,________,_______X,XXXX____,________,
  ________,XXXXX___,________,_______X,XXXX____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,XXXXX___,________,_______X,XXXX____,________,
  ________,XXXXX___,________,_______X,XXXX____,________,
  ________,XXXXX___,________,_______X,XXXX____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,_____XXX,XX______,________,________,________,
  ________,____XXXX,X_______,________,________,________,
  ________,____XXXX,________,________,________,________,
  ________,___XXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ________,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  _______X,XXXXXXXX,________,___XXXXX,X_______,________,
  ______XX,XXXXXXXX,X_______,___XXXXX,________,________,
  ____XXXX,XXX__XXX,XXX_____,__XXXXX_,________,________,
  ___XXXXX,XX____XX,XXXX____,XXXXXX__,________,________,
  _____XXX,_______X,XXXXXX_X,XXXXX___,________,________,
  ________,________,_XXXXXXX,XXXX____,________,________,
  ________,________,__XXXXXX,XX______,________,________,
  ________,________,_XXXXXXX,XXXXXX__,________,________,
  ________,____XXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  __XXXXXX,XXXXXXXX,XXXX____,XXXXXXXX,XXXXXXXX,XX______,
  __XXXXXX,XXXXXXXX,X_______,____XXXX,XXXXXXXX,X_______,
  ___XXXXX,XXXXX___,________,________,_XXXXXXX,X_______,
  ___XXX__,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_59CB[252] = { /* code 59CB */
  ______XX,________,________,________,________,________,
  ______XX,XXX_____,________,_XXX____,________,________,
  ______XX,XXX_____,________,XXXXXX__,________,________,
  ______XX,XX______,________,XXXXX___,________,________,
  ______XX,XX______,_______X,XXXXX___,________,________,
  ______XX,XX______,_______X,XXXX____,________,________,
  ______XX,XX______,_______X,XXX_____,________,________,
  ______XX,XX______,______XX,XXX_____,________,________,
  _____XXX,XX______,______XX,XX______,XXX_____,________,
  _____XXX,X_______,_____XXX,X______X,XXXX____,________,
  XXXXXXXX,XXXXXXXX,X___XXXX,X______X,XXXXX___,________,
  XXXXXXXX,XXXXXXXX,X___XXXX,________,XXXXXX__,________,
  XXXXXXXX,XXXXXXXX,X__XXXX_,________,_XXXXX__,________,
  _____XXX,X___XXXX,X_XXXXX_,________,__XXXXX_,________,
  ____XXXX,X___XXXX,_XXXXX__,_______X,XXXXXXXX,________,
  ____XXXX,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,____XXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ____XXXX,____XXXX,_XXXXXXX,XXXX____,_____XXX,X_______,
  ____XXXX,____XXXX,__XXX___,________,______XX,________,
  ___XXXX_,___XXXXX,________,________,________,________,
  ___XXXX_,___XXXX_,________,________,________,________,
  ___XXXX_,___XXXX_,________,________,________,________,
  __XXXXX_,___XXXX_,________,________,________,________,
  __XXXX__,__XXXXX_,___XXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXX__,__XXXX__,___XXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXX_,__XXXX__,___XXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,XXXXXX__,___XXXX_,________,___XXXX_,________,
  ____XXXX,XXXXX___,___XXXX_,________,___XXXX_,________,
  _____XXX,XXXXX___,___XXXX_,________,___XXXX_,________,
  _______X,XXXXX___,___XXXX_,________,___XXXX_,________,
  _______X,XXXXXX__,___XXXX_,________,___XXXX_,________,
  _______X,XXXXXXX_,___XXXX_,________,___XXXX_,________,
  ______XX,XXXXXXXX,X__XXXX_,________,___XXXX_,________,
  ______XX,XXX_XXXX,XX_XXXX_,________,___XXXX_,________,
  _____XXX,XX___XXX,XX_XXXX_,________,___XXXX_,________,
  ____XXXX,X_____XX,X__XXXXX,XXXXXXXX,XXXXXXX_,________,
  ___XXXXX,X_______,___XXXXX,XXXXXXXX,XXXXXXX_,________,
  __XXXXXX,________,___XXXXX,XXXXXXXX,XXXXXXX_,________,
  _XXXXXX_,________,___XXXX_,________,___XXXX_,________,
  XXXXXX__,________,___XXXX_,________,___XXXX_,________,
  __XXX___,________,___XXXX_,________,___XXXX_,________,
  ________,________,___XXXX_,________,___XXXX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_5B89[205] = { /* code 5B89 */
  ________,________,_XX_____,________,________,
  ________,_______X,XXXX____,________,________,
  ________,_______X,XXXXX___,________,________,
  ________,________,XXXXX___,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,__XX____,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,
  __XXXXX_,________,________,________,XXXX____,
  __XXXXX_,______XX,X_______,________,XXXX____,
  __XXXXX_,______XX,XXX_____,________,XXXX____,
  __XXXXX_,______XX,XXX_____,________,XXXX____,
  __XXXXX_,_____XXX,XX______,________,XXXX____,
  ________,_____XXX,XX______,________,________,
  ________,_____XXX,X_______,________,________,
  ________,____XXXX,X_______,________,________,
  ________,____XXXX,________,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  ________,__XXXX__,________,__XXXX__,________,
  ________,_XXXXX__,________,_XXXXX__,________,
  ________,_XXXX___,________,_XXXXX__,________,
  ________,XXXXX___,________,XXXXX___,________,
  _______X,XXXX____,________,XXXXX___,________,
  _______X,XXXXXX__,_______X,XXXX____,________,
  ______XX,XXXXXXXX,X_____XX,XXX_____,________,
  ________,_XXXXXXX,XXXXXXXX,XXX_____,________,
  ________,_____XXX,XXXXXXXX,XX______,________,
  ________,________,XXXXXXXX,XX______,________,
  ________,________,__XXXXXX,XXXXX___,________,
  ________,________,XXXXXXXX,XXXXXXX_,________,
  ________,______XX,XXXXXX__,XXXXXXXX,X_______,
  ________,___XXXXX,XXXX____,__XXXXXX,XXX_____,
  ________,XXXXXXXX,XX______,____XXXX,XXXXX___,
  __XXXXXX,XXXXXXXX,________,______XX,XXXXXXX_,
  _XXXXXXX,XXXXXX__,________,_______X,XXXXXX__,
  _XXXXXXX,XXX_____,________,________,_XXXX___,
  __XXXXX_,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_5B9A[246] = { /* code 5B9A */
  ________,________,____XX__,________,________,________,
  ________,________,__XXXXX_,________,________,________,
  ________,________,__XXXXXX,________,________,________,
  ________,________,___XXXXX,________,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,________,________,________,
  ________,________,____XX__,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,X_______,________,________,____XXXX,________,
  ____XXXX,X_______,________,________,____XXXX,________,
  ____XXXX,X_______,________,________,____XXXX,________,
  ____XXXX,X_______,________,________,____XXXX,________,
  ________,________,________,________,________,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,__XXX___,____XXXX,X_______,________,________,
  ________,__XXXXX_,____XXXX,X_______,________,________,
  ________,_XXXXX__,____XXXX,X_______,________,________,
  ________,_XXXXX__,____XXXX,XXXXXXXX,XXXXXX__,________,
  ________,_XXXX___,____XXXX,XXXXXXXX,XXXXXX__,________,
  ________,XXXXX___,____XXXX,XXXXXXXX,XXXXXX__,________,
  ________,XXXXX___,____XXXX,X_______,________,________,
  _______X,XXXXX___,____XXXX,X_______,________,________,
  _______X,XXXXXX__,____XXXX,X_______,________,________,
  _______X,XXXXXXX_,____XXXX,X_______,________,________,
  ______XX,XXXXXXXX,____XXXX,X_______,________,________,
  _____XXX,XXXXXXXX,X___XXXX,X_______,________,________,
  _____XXX,XX__XXXX,XXX_XXXX,X_______,________,________,
  ____XXXX,X_____XX,XXXXXXXX,X_______,________,________,
  ___XXXXX,X______X,XXXXXXXX,XXX_____,_____XXX,XX______,
  __XXXXXX,________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXXXX_,________,___XXXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXX__,________,______XX,XXXXXXXX,XXXXXXXX,X_______,
  ___XX___,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_5B9E[210] = { /* code 5B9E */
  ________,________,__XXX___,________,________,
  ________,________,XXXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXX__,________,________,
  ________,________,_XXXXXX_,________,________,
  ________,________,__XXXXX_,________,________,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXX_,________,________,________,__XXXX__,
  __XXXXX_,________,________,________,__XXXX__,
  __XXXXX_,________,________,________,__XXXX__,
  __XXXXX_,________,______XX,XXX_____,__XXXXX_,
  __XXXXX_,__XXXX__,______XX,XXX_____,__XXXXX_,
  ________,_XXXXXXX,______XX,XXX_____,________,
  ________,__XXXXXX,X_____XX,XX______,________,
  ________,____XXXX,XXX___XX,XX______,________,
  ________,_____XXX,XXXX__XX,XX______,________,
  _____XXX,_______X,XXX___XX,XX______,________,
  ____XXXX,XX______,XX____XX,XX______,________,
  ____XXXX,XXX_____,_____XXX,XX______,________,
  ______XX,XXXXX___,_____XXX,XX______,________,
  _______X,XXXXXX__,_____XXX,XX______,________,
  ________,_XXXXX__,_____XXX,X_______,________,
  ________,__XXX___,_____XXX,X_______,________,
  ________,________,_____XXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  ________,________,___XXXXX,________,________,
  ________,________,___XXXX_,________,________,
  ________,________,__XXXXX_,_XX_____,________,
  ________,________,_XXXXX__,XXXXX___,________,
  ________,_______X,XXXXX__X,XXXXXX__,________,
  ________,______XX,XXXX____,XXXXXXXX,________,
  ________,___XXXXX,XXX_____,__XXXXXX,XX______,
  ________,_XXXXXXX,XX______,____XXXX,XXXX____,
  _____XXX,XXXXXXXX,________,______XX,XXXXXX__,
  _XXXXXXX,XXXXXX__,________,_______X,XXXXXXXX,
  __XXXXXX,XXXX____,________,________,_XXXXXX_,
  ___XXXXX,X_______,________,________,___XXX__,
  ___XX___,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_5EA6[252] = { /* code 5EA6 */
  ________,________,_____XXX,________,________,________,
  ________,________,___XXXXX,________,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,X_______,________,________,________,________,
  ____XXXX,X______X,XXXX____,____XXXX,X_______,________,
  ____XXXX,X______X,XXXX____,____XXXX,X_______,________,
  ____XXXX,X______X,XXXX____,____XXXX,X_______,________,
  ____XXXX,X______X,XXXX____,____XXXX,X_______,________,
  ____XXXX,X______X,XXXX____,____XXXX,X_______,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXX__X,XXXX____,____XXXX,X___XXX_,________,
  ____XXXX,X______X,XXXX____,____XXXX,X_______,________,
  ____XXXX,X______X,XXXX____,____XXXX,X_______,________,
  ____XXXX,X______X,XXXX____,____XXXX,X_______,________,
  ____XXXX,X______X,XXXXXXXX,XXXXXXXX,X_______,________,
  ____XXXX,_______X,XXXXXXXX,XXXXXXXX,X_______,________,
  ____XXXX,_______X,XXXXXXXX,XXXXXXXX,X_______,________,
  ____XXXX,________,________,________,________,________,
  ____XXXX,________,________,________,________,________,
  ____XXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ____XXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XXX_____,________,
  ____XXXX,__XXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  ____XXXX,_______X,XXXX____,_____XXX,XX______,________,
  ___XXXXX,________,XXXX____,____XXXX,X_______,________,
  ___XXXX_,________,XXXXX___,___XXXXX,________,________,
  ___XXXX_,________,_XXXXX__,__XXXXX_,________,________,
  ___XXXX_,________,__XXXXX_,_XXXXX__,________,________,
  __XXXXX_,________,___XXXXX,XXXXXX__,________,________,
  __XXXXX_,________,____XXXX,XXXXX___,________,________,
  __XXXX__,________,_____XXX,XXX_____,________,________,
  _XXXXX__,________,___XXXXX,XXXXXX__,________,________,
  _XXXX___,_______X,XXXXXXXX,XXXXXXXX,XXX_____,________,
  XXXXX___,__XXXXXX,XXXXXXX_,_XXXXXXX,XXXXXXXX,X_______,
  _XXXX__X,XXXXXXXX,XXXX____,_____XXX,XXXXXXXX,X_______,
  ________,XXXXXXXX,________,________,_XXXXXXX,________,
  ________,_XX_____,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_5F00[234] = { /* code 5F00 */
  ____XXXX,X_______,________,________,___XXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,XX______,__XXXXX_,________,________,
  ________,_____XXX,X_______,__XXXXX_,________,________,
  ________,____XXXX,X_______,__XXXXX_,________,________,
  ________,____XXXX,X_______,__XXXXX_,________,________,
  ________,___XXXXX,X_______,__XXXXX_,________,________,
  ________,___XXXXX,________,__XXXXX_,________,________,
  ________,__XXXXXX,________,__XXXXX_,________,________,
  ________,__XXXXX_,________,__XXXXX_,________,________,
  ________,_XXXXXX_,________,__XXXXX_,________,________,
  ________,XXXXXX__,________,__XXXXX_,________,________,
  _______X,XXXXX___,________,__XXXXX_,________,________,
  ______XX,XXXXX___,________,__XXXXX_,________,________,
  _____XXX,XXXX____,________,__XXXXX_,________,________,
  ___XXXXX,XXX_____,________,__XXXXX_,________,________,
  __XXXXXX,XX______,________,__XXXXX_,________,________,
  ____XXXX,X_______,________,__XXXXX_,________,________,
  _____XX_,________,________,__XXXXX_,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_62A4[252] = { /* code 62A4 */
  ________,________,________,____XX__,________,________,
  _______X,XXXX____,________,__XXXXX_,________,________,
  _______X,XXXX____,________,___XXXXX,________,________,
  _______X,XXXX____,________,___XXXXX,________,________,
  _______X,XXXX____,________,____XXXX,X_______,________,
  _______X,XXXX____,________,____XXXX,X_______,________,
  _______X,XXXX____,________,_____XX_,________,________,
  _______X,XXXX____,________,________,________,________,
  _______X,XXXX____,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _______X,XXXX____,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _______X,XXXX____,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _XXXXXXX,XXXXXXXX,XX__XXXX,________,____XXXX,X_______,
  _XXXXXXX,XXXXXXXX,XX__XXXX,________,____XXXX,X_______,
  _XXXXXXX,XXXXXXXX,XX__XXXX,________,____XXXX,X_______,
  _______X,XXXX____,____XXXX,________,____XXXX,X_______,
  _______X,XXXX____,____XXXX,________,____XXXX,X_______,
  _______X,XXXX____,____XXXX,________,____XXXX,________,
  _______X,XXXX____,____XXXX,________,____XXXX,________,
  _______X,XXXX____,____XXXX,________,____XXXX,________,
  _______X,XXXX____,XX__XXXX,________,____XXXX,________,
  _______X,XXXXXXXX,XX__XXXX,XXXXXXXX,XXXXXXXX,________,
  _______X,XXXXXXXX,XX__XXXX,XXXXXXXX,XXXXXXXX,X_______,
  __XXXXXX,XXXXXXXX,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXX____,____XXXX,________,____XXXX,X_______,
  _XXXXXXX,XXXX____,____XXXX,________,____XXXX,X_______,
  _XXX___X,XXXX____,____XXXX,________,________,________,
  _______X,XXXX____,___XXXXX,________,________,________,
  _______X,XXXX____,___XXXXX,________,________,________,
  _______X,XXXX____,___XXXX_,________,________,________,
  _______X,XXXX____,___XXXX_,________,________,________,
  _______X,XXXX____,___XXXX_,________,________,________,
  _______X,XXXX____,__XXXXX_,________,________,________,
  _______X,XXXX____,__XXXXX_,________,________,________,
  _______X,XXXX____,__XXXX__,________,________,________,
  _______X,XXXX____,_XXXXX__,________,________,________,
  _______X,XXXX____,_XXXXX__,________,________,________,
  _______X,XXXX____,XXXXX___,________,________,________,
  ___XXXXX,XXXX___X,XXXXX___,________,________,________,
  ___XXXXX,XXX____X,XXXX____,________,________,________,
  ____XXXX,XX____XX,XXX_____,________,________,________,
  ____XXX_,_______X,XXX_____,________,________,________,
  ________,________,XX______,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_65F6[246] = { /* code 65F6 */
  ________,________,________,_______X,XXXX____,________,
  ________,________,________,_______X,XXXX____,________,
  ________,________,________,_______X,XXXX____,________,
  ________,________,________,_______X,XXXX____,________,
  ________,________,________,_______X,XXXX____,________,
  XXXXXXXX,XXXXXXXX,________,_______X,XXXX____,________,
  XXXXXXXX,XXXXXXXX,________,_______X,XXXX____,________,
  XXXXXXXX,XXXXXXXX,________,_______X,XXXX____,________,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  XXXXX___,___XXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXX___,___XXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXX___,___XXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  _XXXXXXX,XXXXXXXX,________,_______X,XXXX____,________,
  _XXXXXXX,XXXXXXXX,________,_______X,XXXX____,________,
  _XXXXXXX,XXXXXXXX,_____XX_,_______X,XXXX____,________,
  _XXXX___,___XXXXX,___XXXXX,_______X,XXXX____,________,
  _XXXX___,___XXXXX,___XXXXX,X______X,XXXX____,________,
  _XXXX___,___XXXXX,____XXXX,X______X,XXXX____,________,
  _XXXX___,___XXXXX,_____XXX,XX_____X,XXXX____,________,
  _XXXX___,___XXXXX,_____XXX,XX_____X,XXXX____,________,
  _XXXX___,___XXXXX,______XX,XXX____X,XXXX____,________,
  XXXXX___,___XXXXX,______XX,XXX____X,XXXX____,________,
  XXXXX___,___XXXXX,______XX,X______X,XXXX____,________,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  XXXXXXXX,XXXXXXXX,________,_______X,XXXX____,________,
  XXXXXXXX,XXXXXXXX,________,_______X,XXXX____,________,
  XXXXXXXX,XXXXXXXX,________,_______X,XXXX____,________,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  XXXXX___,___XXXXX,________,_______X,XXXX____,________,
  XXXXX___,________,________,_______X,XXXX____,________,
  XXXXX___,________,________,_______X,XXXX____,________,
  XXXXX___,________,________,_______X,XXXX____,________,
  ________,________,________,__XXXXXX,XXXX____,________,
  ________,________,________,__XXXXXX,XXX_____,________,
  ________,________,________,___XXXXX,XXX_____,________,
  ________,________,________,___XXXXX,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_671B[200] = { /* code 671B */
  ________,__XX____,________,________,________,
  _______X,XXXX____,________,________,________,
  ________,XXXX____,_____XXX,XXXXXXXX,XXXXXX__,
  ________,XXXXX___,_____XXX,XXXXXXXX,XXXXX___,
  ________,XXXXX___,_____XXX,X_______,_XXXX___,
  XXXX____,_XXXX_XX,XXX__XXX,X_______,_XXXX___,
  XXXXXXXX,XXXXXXXX,XXX__XXX,X_______,_XXXX___,
  XXXXXXXX,XXXXXXXX,XXX__XXX,XXXXXXXX,XXXXX___,
  ____XXXX,________,_____XXX,XXXXXXXX,XXXXX___,
  ____XXXX,________,_____XXX,XXXXXXXX,XXXXX___,
  ____XXXX,________,_____XXX,X_______,_XXXX___,
  ____XXXX,________,_____XXX,X_______,_XXXX___,
  ____XXXX,________,_____XXX,X_______,_XXXX___,
  ____XXXX,________,____XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,______XX,XX__XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XX__XXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XX_XXXXX,________,_XXXX___,
  ____XXXX,XXXXXXX_,___XXXXX,________,_XXXX___,
  ____XXXX,XX______,__XXXXX_,________,_XXXX___,
  ________,________,_XXXXXX_,_____XXX,XXXXX___,
  ________,________,XXXXXX__,_____XXX,XXXXX___,
  ________,________,_XXXX___,______XX,XXXX____,
  ________,________,__XX____,______XX,XX______,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  __XXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,
  ________,________,__XXXX__,________,________,
  ________,________,__XXXX__,________,________,
  ________,________,__XXXX__,________,________,
  ________,________,__XXXX__,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,
  ________,________,__XXXX__,________,________,
  ________,________,__XXXX__,________,________,
  ________,________,__XXXX__,________,________,
  ________,________,__XXXX__,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_671F[240] = { /* code 671F */
  _____XXX,X_______,XXXXX___,________,________,________,
  _____XXX,X_______,XXXXX___,________,________,________,
  _____XXX,X_______,XXXXX___,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,_XXXXX__,____XXXX,X_______,
  _XXXXXXX,XXXXXXXX,XXXXXXXX,_XXXXX__,____XXXX,X_______,
  _XX__XXX,X_______,XXXX__XX,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,XXXXXXXX,XXXX____,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXX____,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,XXXXXXXX,XXXX____,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,XXXXXXXX,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,XXXXXXXX,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXX__,____XXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_______,XXXX____,_XXXXXXX,XXXXXXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,_XXXX___,____XXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,_XXXX___,____XXXX,X_______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,____XXXX,X_______,
  ________,________,________,XXXXX___,____XXXX,X_______,
  _____XXX,_______X,XX______,XXXXX___,____XXXX,X_______,
  _____XXX,XX____XX,XXX_____,XXXX____,____XXXX,X_______,
  ____XXXX,X_____XX,XXXX___X,XXXX____,____XXXX,X_______,
  ___XXXXX,_______X,XXXX___X,XXXX____,____XXXX,X_______,
  ___XXXXX,________,XXXXX_XX,XXX_____,____XXXX,X_______,
  __XXXXX_,________,_XXXXXXX,XXX_____,____XXXX,X_______,
  _XXXXX__,________,_XXX_XXX,XX______,____XXXX,X_______,
  XXXXX___,________,____XXXX,XX______,_XXXXXXX,X_______,
  _XXX____,________,___XXXXX,X_______,_XXXXXXX,________,
  ________,________,____XXXX,________,__XXXXXX,________,
  ________,________,_____XXX,________,__XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_6B62[228] = { /* code 6B62 */
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,XXXXXXXX,XXXXXX__,________,
  _______X,XXXX____,____XXXX,XXXXXXXX,XXXXXX__,________,
  _______X,XXXX____,____XXXX,XXXXXXXX,XXXXXX__,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  _______X,XXXX____,____XXXX,X_______,________,________,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXX_____,________,________,________,_______X,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_6C14[252] = { /* code 6C14 */
  ________,_XXX____,________,________,________,________,
  ________,_XXXXX__,________,________,________,________,
  ________,XXXXXX__,________,________,________,________,
  ________,XXXXX___,________,________,________,________,
  _______X,XXXX____,________,________,________,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  _____XXX,XX______,________,________,________,________,
  ____XXXX,XX______,________,________,________,________,
  ____XXXX,X_______,________,________,________,________,
  ___XXXXX,________,________,________,________,________,
  __XXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  _XXXXXX_,_XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  XXXXXX__,_XXXXXXX,XXXXXXXX,XXXXXXXX,XX______,________,
  _XXXX___,________,________,________,________,________,
  ___XX___,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,____XXXX,X_______,________,
  ________,________,________,_____XXX,X____XXX,________,
  ________,________,________,_____XXX,XX__XXXX,X_______,
  ________,________,________,_____XXX,XX__XXXX,X_______,
  ________,________,________,______XX,XXX_XXXX,X_______,
  ________,________,________,______XX,XXXXXXXX,________,
  ________,________,________,______XX,XXXXXXXX,________,
  ________,________,________,_______X,XXXXXXX_,________,
  ________,________,________,________,XXXXXX__,________,
  ________,________,________,________,_XXXXX__,________,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_6C27[252] = { /* code 6C27 */
  ________,__XXX___,________,________,________,________,
  ________,__XXXXX_,________,________,________,________,
  ________,_XXXXXX_,________,________,________,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ________,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  ______XX,XXXX____,________,________,________,________,
  _____XXX,XXX_____,________,________,________,________,
  ____XXXX,XX______,________,________,________,________,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  __XXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _XXXXXX_,_XXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  __XXXX__,________,________,________,________,________,
  ___XX___,________,________,________,________,________,
  ________,________,________,________,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,___XX___,________,________,XXXX____,________,
  ________,__XXXX__,______XX,X_______,XXXX____,________,
  ________,__XXXXX_,_____XXX,XXX_____,XXXX____,________,
  ________,___XXXXX,_____XXX,XX______,XXXX____,________,
  ________,____XXXX,____XXXX,X_______,XXXX____,________,
  ____XXXX,____XX__,____XXXX,________,XXXX____,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,XXXX____,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,XXXX____,________,
  ________,________,XXXX____,________,XXXX____,________,
  ________,________,XXXX____,________,XXXX____,________,
  ________,________,XXXX____,________,XXXX____,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,XXXX____,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,XXXXX___,________,
  _____XXX,XXXXXXXX,XXXXXXXX,XXXX____,_XXXX___,________,
  ________,________,XXXX____,________,_XXXX___,________,
  ________,________,XXXX____,________,_XXXX___,________,
  ________,________,XXXX____,________,_XXXX_XX,X_______,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,_XXXXXXX,XXX_____,
  ___XXXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,__XXXXXX,XXX_____,
  ___XX___,________,XXXX____,________,__XXXXXX,XX______,
  ________,________,XXXX____,________,__XXXXXX,XX______,
  ________,________,XXXX____,________,___XXXXX,X_______,
  ________,________,XXXX____,________,____XXXX,________,
  ________,________,XXXX____,________,_____XX_,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_6D4B[240] = { /* code 6D4B */
  ________,________,________,________,_____XXX,X_______,
  ____XXX_,________,________,________,_____XXX,X_______,
  ___XXXXX,________,________,________,_____XXX,X_______,
  ___XXXXX,XX__XXXX,XXXXXXXX,XXXX____,_____XXX,X_______,
  ____XXXX,XXX_XXXX,XXXXXXXX,XXXX____,_____XXX,X_______,
  ______XX,XXX_XXXX,XXXXXXXX,XXXX____,_____XXX,X_______,
  _______X,XX___XXX,X_______,XXXX__XX,XXX__XXX,X_______,
  ________,XX___XXX,X_______,XXXX__XX,XXX__XXX,X_______,
  ________,_____XXX,X_______,XXXX__XX,XXX__XXX,X_______,
  ________,_____XXX,X_XX____,XXXX__XX,XXX__XXX,X_______,
  ________,_____XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  ___XX___,_____XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  __XXXX__,_____XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  _XXXXXX_,_____XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  __XXXXXX,_____XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  ___XXXXX,X____XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  ____XXXX,XXX__XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  _____XXX,XX___XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  ______XX,X____XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  ________,_____XXX,X_XXXXX_,XXXX__XX,XXX__XXX,X_______,
  ________,_____XXX,X_XXXX__,XXXX__XX,XXX__XXX,X_______,
  ________,_____XXX,X_XXXX__,XXXX__XX,XXX__XXX,X_______,
  ________,XX___XXX,X_XXXX__,XXXX__XX,XXX__XXX,X_______,
  _______X,XXX_XXXX,X_XXXX__,XXXX__XX,XXX__XXX,X_______,
  _______X,XXXXXXXX,X_XXXX__,XXXX__XX,XXX__XXX,X_______,
  ______XX,XXX_XXXX,X_XXXX__,XXXX__XX,XXX__XXX,X_______,
  ______XX,XXX_XXXX,XXXXXX__,XXXX__XX,XXX__XXX,X_______,
  ______XX,XX______,_XXXXX__,______XX,XXX__XXX,X_______,
  _____XXX,XX______,_XXXX___,______XX,XXX__XXX,X_______,
  _____XXX,X_______,XXXXX_XX,X_____XX,XXX__XXX,X_______,
  ____XXXX,X_______,XXXXXXXX,XX______,_____XXX,X_______,
  ____XXXX,_______X,XXXXXXXX,XX______,_____XXX,X_______,
  ___XXXXX,_______X,XXXX__XX,XXX_____,_____XXX,X_______,
  __XXXXX_,______XX,XXX____X,XXXX____,_____XXX,X_______,
  __XXXXX_,______XX,XXX____X,XXXXX___,_____XXX,X_______,
  _XXXXXX_,_____XXX,XX______,XXXXX___,_____XXX,X_______,
  _XXXXX__,____XXXX,X_______,_XXXXX__,_XXXXXXX,X_______,
  __XXXX__,___XXXXX,X_______,_XXXX___,_XXXXXXX,X_______,
  ________,___XXXXX,________,__XX____,__XXXXXX,________,
  ________,_____XX_,________,________,__XXXX__,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_6D53[246] = { /* code 6D53 */
  ________,________,________,XXX_____,________,________,
  ____XX__,________,________,XXXXX___,________,________,
  ___XXXX_,________,________,XXXXX___,________,________,
  ___XXXXX,________,________,XXXXX___,________,________,
  ___XXXXX,XX______,________,XXXX____,________,________,
  ____XXXX,XXX_____,_______X,XXXX____,________,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  _______X,XXX_XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,XXX_XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,____XXXX,X______X,XXX_____,___XXXXX,________,
  ________,____XXXX,X_____XX,XXX_____,___XXXXX,________,
  ________,____XXXX,X_____XX,XXX_____,___XXXXX,________,
  _XXX____,____XXXX,X_____XX,XX______,___XXXXX,________,
  _XXXXX__,____XXXX,X____XXX,XXX_____,___XXXXX,________,
  _XXXXXXX,________,_____XXX,XXX_____,________,________,
  XXXXXXXX,X_______,_____XXX,XXX_____,________,________,
  ___XXXXX,XXX_____,____XXXX,XXXX____,________,________,
  _____XXX,XX______,____XXXX,XXXX____,________,________,
  ______XX,X_______,___XXXXX,XXXX____,___XX___,________,
  ________,________,___XXXX_,XXXXX___,___XXX__,________,
  ________,________,__XXXXX_,_XXXX___,__XXXXX_,________,
  ________,________,_XXXXX__,_XXXXX__,_XXXXXX_,________,
  ________,________,XXXXXX__,_XXXXX__,XXXXXX__,________,
  ______XX,________,XXXXXX__,__XXXX_X,XXXX____,________,
  ______XX,X______X,XXXXXX__,__XXXXXX,XXX_____,________,
  ______XX,XX____XX,XXXXXX__,___XXXXX,XX______,________,
  _____XXX,XX___XXX,XXXXXX__,___XXXXX,X_______,________,
  _____XXX,XX__XXXX,XXXXXX__,____XXXX,________,________,
  _____XXX,X__XXXXX,X_XXXX__,____XXXX,X_______,________,
  ____XXXX,XXXXXXXX,__XXXX__,_____XXX,XX______,________,
  ____XXXX,__XXXXX_,__XXXX__,_____XXX,XXX_____,________,
  ___XXXXX,___XXX__,__XXXX__,_XX___XX,XXXX____,________,
  ___XXXXX,________,__XXXX__,XXXX___X,XXXXX___,________,
  ___XXXX_,________,__XXXX_X,XXXX___X,XXXXXX__,________,
  __XXXXX_,________,__XXXXXX,XXXXX___,XXXXXXX_,________,
  __XXXXX_,________,__XXXXXX,XXX_____,_XXXXXXX,________,
  _XXXXX__,________,__XXXXXX,XX______,__XXXXXX,XX______,
  XXXXXX__,________,__XXXXXX,X_______,___XXXXX,X_______,
  XXXXXX__,________,_XXXXXX_,________,_____XXX,________,
  ___XX___,________,__XXXX__,________,______XX,________,
  ________,________,___XX___,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_6E29[240] = { /* code 6E29 */
  ________,________,________,________,________,________,
  ___XXXX_,______XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  __XXXXXX,______XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ___XXXXX,X_____XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ____XXXX,XX____XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ______XX,XXXX__XX,XX______,________,XXXX____,________,
  _______X,XXX___XX,XX______,________,XXXX____,________,
  ________,XX____XX,XX______,________,XXXX____,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _XXXX___,______XX,XX______,________,XXXX____,________,
  _XXXXX__,______XX,XX______,________,XXXX____,________,
  _XXXXXX_,______XX,XX______,________,XXXX____,________,
  ___XXXXX,X_____XX,XX______,________,XXXX____,________,
  ____XXXX,XX____XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  _____XXX,X_____XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ______XX,______XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ________,________,________,________,________,________,
  ______XX,____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XX__XXXX,XXXXXXXX,XXXXXXXX,XXXXXXX_,________,
  _____XXX,XX__XXXX,XXXXXXXX,XXXXXXXX,XXXXXX__,________,
  _____XXX,X___XXXX,____XXX_,___XXXX_,__XXXX__,________,
  _____XXX,X___XXXX,____XXX_,___XXXX_,__XXXX__,________,
  ____XXXX,X___XXXX,____XXX_,___XXXX_,__XXXX__,________,
  ____XXXX,____XXXX,____XXX_,___XXXX_,__XXXX__,________,
  ___XXXXX,____XXXX,____XXX_,___XXXX_,__XXXX__,________,
  ___XXXXX,____XXXX,____XXX_,___XXXX_,__XXXX__,________,
  ___XXXX_,____XXXX,____XXX_,___XXXX_,__XXXX__,________,
  __XXXXX_,____XXXX,____XXX_,___XXXX_,__XXXX__,________,
  __XXXXX_,____XXXX,____XXX_,___XXXX_,__XXXX__,________,
  _XXXXX__,____XXXX,____XXX_,___XXXX_,__XXXX__,________,
  _XXXXX__,____XXXX,____XXX_,___XXXX_,__XXXX__,________,
  XXXXXX__,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _XXXX___,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  __XXX___,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,________,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_7406[228] = { /* code 7406 */
  ________,________,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ________,________,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXXXXXX,XXXXXXXX,_XXXX___,__XXXX__,___XXXXX,________,
  XXXXXXXX,XXXXXXXX,_XXXX___,__XXXX__,___XXXXX,________,
  ______XX,XX______,_XXXX___,__XXXX__,___XXXXX,________,
  ______XX,XX______,_XXXX___,__XXXX__,___XXXXX,________,
  ______XX,XX______,_XXXX___,__XXXX__,___XXXXX,________,
  ______XX,XX______,_XXXX___,__XXXX__,___XXXXX,________,
  ______XX,XX______,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX______,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX______,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX______,_XXXX___,__XXXX__,___XXXXX,________,
  ______XX,XX______,_XXXX___,__XXXX__,___XXXXX,________,
  ______XX,XX___XX_,_XXXX___,__XXXX__,___XXXXX,________,
  XXXXXXXX,XXXXXXX_,_XXXX___,__XXXX__,___XXXXX,________,
  XXXXXXXX,XXXXXXX_,_XXXX___,__XXXX__,___XXXXX,________,
  XXXXXXXX,XXXXXXX_,_XXXX___,__XXXX__,___XXXXX,________,
  ______XX,XX______,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX______,_XXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX______,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX______,________,__XXXX__,________,________,
  ______XX,XX______,________,__XXXX__,________,________,
  ______XX,XX______,________,__XXXX__,________,________,
  ______XX,XX______,________,__XXXX__,________,________,
  ______XX,XX______,________,__XXXX__,________,________,
  ______XX,XX______,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XX__XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  ______XX,XXXXXXXX,________,__XXXX__,________,________,
  ____XXXX,XXXXX___,________,__XXXX__,________,________,
  _XXXXXXX,XXX_____,________,__XXXX__,________,________,
  XXXXXXXX,________,________,__XXXX__,________,________,
  XXXXXX__,________,________,__XXXX__,________,________,
  _XXX____,________,________,__XXXX__,________,________,
  ________,______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  ________,______XX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_8BA1[240] = { /* code 8BA1 */
  ________,________,________,_XXXXX__,________,________,
  _____XXX,________,________,__XXXX__,________,________,
  ____XXXX,X_______,________,__XXXX__,________,________,
  ____XXXX,XX______,________,__XXXX__,________,________,
  _____XXX,XXX_____,________,__XXXX__,________,________,
  ______XX,XXXX____,________,__XXXX__,________,________,
  _______X,XXXXX___,________,__XXXX__,________,________,
  ________,XXXXXX__,________,__XXXX__,________,________,
  ________,_XXXXX__,________,__XXXX__,________,________,
  ________,__XX____,________,__XXXX__,________,________,
  ________,________,________,__XXXX__,________,________,
  ________,________,________,__XXXX__,________,________,
  ________,________,________,__XXXX__,________,________,
  ________,________,________,__XXXX__,________,________,
  XXXXXXXX,XXX__XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXX__XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXX__XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XXX___XX,X_______,__XXXX__,________,________,
  _______X,XXX__XXX,XX______,__XXXX__,________,________,
  _______X,XXX_XXXX,XX______,__XXXX__,________,________,
  _______X,XXXXXXXX,X_______,__XXXX__,________,________,
  _______X,XXXXXXXX,________,__XXXX__,________,________,
  _______X,XXXXXXX_,________,__XXXX__,________,________,
  _______X,XXXXXX__,________,__XXXX__,________,________,
  _______X,XXXXX___,________,__XXXX__,________,________,
  ______XX,XXXX____,________,__XXXX__,________,________,
  _______X,XXX_____,________,__XXXX__,________,________,
  _______X,XX______,________,__XXXX__,________,________,
  ________,________,________,_XXXXX__,________,________,
  ________,________,________,_XXXXX__,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_8BBE[246] = { /* code 8BBE */
  ____XXX_,________,________,________,________,________,
  ___XXXXX,________,__XXXXXX,XXXXXXXX,X_______,________,
  ____XXXX,X_______,__XXXXXX,XXXXXXXX,X_______,________,
  _____XXX,XX______,__XXXXXX,XXXXXXXX,X_______,________,
  _____XXX,XXX_____,__XXXX__,_____XXX,X_______,________,
  ______XX,XXXX____,__XXXX__,_____XXX,X_______,________,
  _______X,XXXXX___,__XXXX__,_____XXX,X_______,________,
  ________,XXXX____,_XXXXX__,_____XXX,X_______,________,
  ________,_XX_____,_XXXXX__,_____XXX,X_______,________,
  ________,________,_XXXXX__,_____XXX,X_______,________,
  ________,________,_XXXX___,_____XXX,X_______,________,
  ________,________,XXXXX___,_____XXX,X_______,________,
  ________,________,XXXXX___,_____XXX,XX______,________,
  XXXXXXXX,XXX____X,XXXX____,_____XXX,XXXXXXXX,X_______,
  XXXXXXXX,XXX___XX,XXX_____,_____XXX,XXXXXXXX,X_______,
  XXXXXXXX,XXX_XXXX,XX______,_____XXX,XXXXXXXX,X_______,
  ______XX,XX____XX,X_______,________,________,________,
  ______XX,XX____XX,________,________,________,________,
  ______XX,XX____XX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ______XX,XX____XX,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  ______XX,XX____XX,XXXXXXXX,XXXXXXXX,XXXX____,________,
  ______XX,XX______,_XXXX___,_______X,XXXX____,________,
  ______XX,XX______,_XXXXX__,_______X,XXXX____,________,
  ______XX,XX______,__XXXX__,______XX,XXX_____,________,
  ______XX,XX______,__XXXX__,______XX,XXX_____,________,
  ______XX,XX______,__XXXXX_,_____XXX,XX______,________,
  ______XX,XX______,___XXXX_,_____XXX,XX______,________,
  ______XX,XX___XX_,___XXXXX,____XXXX,X_______,________,
  ______XX,XX__XXX_,____XXXX,X__XXXXX,________,________,
  ______XX,XX_XXXX_,_____XXX,XX_XXXXX,________,________,
  ______XX,XXXXXXXX,_____XXX,XXXXXXX_,________,________,
  ______XX,XXXXXXX_,______XX,XXXXXX__,________,________,
  ______XX,XXXXXX__,_______X,XXXXXX__,________,________,
  ______XX,XXXXX___,______XX,XXXXXX__,________,________,
  ______XX,XXXX____,_____XXX,XXXXXXXX,________,________,
  _____XXX,XXX_____,___XXXXX,XXXXXXXX,XXX_____,________,
  _____XXX,XX______,XXXXXXXX,____XXXX,XXXXXXX_,________,
  ______XX,X____XXX,XXXXXX__,______XX,XXXXXXXX,XX______,
  _______X,X__XXXXX,XXXX____,________,_XXXXXXX,X_______,
  ________,____XXXX,XX______,________,____XXXX,________,
  ________,_____XX_,________,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_9189[246] = { /* code 9189 */
  ________,________,________,____XXXX,________,________,
  ________,________,________,___XXXXX,________,________,
  ________,________,________,____XXXX,________,________,
  XXXXXXXX,XXXXXXXX,XXX_____,____XXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXX_____,_____XXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXX_____,_____XX_,________,________,
  _____XXX,X_XXXX__,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_XXXX__,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_XXXX__,____XXXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_XXXX__,________,________,________,________,
  _____XXX,X_XXXX__,________,________,________,________,
  XXXXXXXX,XXXXXXXX,XXX_____,XX______,__XXX___,________,
  XXXXXXXX,XXXXXXXX,XXX____X,XXXX____,__XXXXX_,________,
  XXXXXXXX,XXXXXXXX,XXX____X,XXXX____,_XXXXX__,________,
  XXXX_XXX,X_XXXX_X,XXX____X,XXX_____,_XXXX___,________,
  XXXX_XXX,X_XXXX_X,XXX___XX,XXX_____,_XXXX___,________,
  XXXX_XXX,X_XXXX_X,XXX___XX,XXXX____,XXXXX___,________,
  XXXX_XXX,X_XXXX_X,XXX__XXX,XXXXX___,XXXXXX__,________,
  XXXX_XXX,X_XXXX_X,XXX__XXX,XXXXXXXX,XXXXXXXX,________,
  XXXX_XXX,X_XXXX_X,XXX_XXXX,X_XXXXXX,XXX_XXXX,X_______,
  XXXX_XXX,__XXXX_X,XXXXXXXX,___XX_XX,XXX__XXX,XX______,
  XXXX_XXX,__XXXX_X,XXXXXXX_,_____XXX,XX____XX,X_______,
  XXXX_XXX,__XXXX_X,XXX_XXX_,______XX,X_____XX,________,
  XXXXXXXX,__XXXXXX,XXX_____,________,________,________,
  XXXXXXXX,___XXXXX,XXX_____,____XXXX,X_______,________,
  XXXXXXXX,___XXXXX,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XX______,
  XXXXXXXX,XXXXXXXX,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXX_____,____XXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXX_____,____XXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXX_____,____XXXX,X_______,________,
  XXXXXXXX,XXXXXXXX,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXX_____,____XXXX,X_______,________,
  XXXX____,_______X,XXX_____,____XXXX,X_______,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_9645[228] = { /* code 9645 */
  XXXXXXXX,XXXXXX__,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXX__,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXXXXXX,XXXXXX__,XXXXXXXX,XXXXXXXX,XXXXX___,________,
  XXXX____,_XXXX___,________,________,________,________,
  XXXX____,XXXXX___,________,________,________,________,
  XXXX____,XXXXX___,________,________,________,________,
  XXXX____,XXXX____,________,________,________,________,
  XXXX___X,XXXX____,________,________,________,________,
  XXXX___X,XXXX____,________,________,________,________,
  XXXX___X,XXXX____,________,________,________,________,
  XXXX___X,XXX_____,________,________,________,________,
  XXXX__XX,XXX__XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXX__XX,XXX__XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXX__XX,XX___XXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,________,
  XXXX__XX,XXX_____,________,XXXXX___,________,________,
  XXXX___X,XXX_____,________,XXXXX___,________,________,
  XXXX___X,XXXX____,________,XXXXX___,________,________,
  XXXX____,XXXX____,________,XXXXX___,________,________,
  XXXX____,XXXXX___,________,XXXXX___,________,________,
  XXXX____,_XXXX___,_XXX____,XXXXX__X,XXX_____,________,
  XXXX____,_XXXXX__,_XXXXX__,XXXXX_XX,XXX_____,________,
  XXXX____,_XXXXX__,XXXXX___,XXXXX_XX,XXXX____,________,
  XXXX____,_XXXXX__,XXXXX___,XXXXX__X,XXXX____,________,
  XXXX____,_XXXXX__,XXXX____,XXXXX__X,XXXXX___,________,
  XXXX____,XXXXX__X,XXXX____,XXXXX___,XXXXX___,________,
  XXXXXXXX,XXXXX__X,XXXX____,XXXXX___,XXXXXX__,________,
  XXXXXXXX,XXXX__XX,XXX_____,XXXXX___,_XXXXX__,________,
  XXXX_XXX,XXX___XX,XXX_____,XXXXX___,_XXXXXX_,________,
  XXXX_XXX,XX___XXX,XX______,XXXXX___,__XXXXX_,________,
  XXXX____,_____XXX,XX______,XXXXX___,__XXXXXX,________,
  XXXX____,____XXXX,X_______,XXXXX___,___XXXXX,________,
  XXXX____,____XXXX,X_______,XXXXX___,___XXXXX,X_______,
  XXXX____,___XXXXX,________,XXXXX___,____XX__,________,
  XXXX____,_____XXX,___XXXXX,XXXXX___,________,________,
  XXXX____,________,____XXXX,XXXXX___,________,________,
  XXXX____,________,____XXXX,XXXX____,________,________,
  XXXX____,________,____XXXX,XXX_____,________,________,
  XXXX____,________,____XXX_,________,________,________};

GUI_CONST_STORAGE unsigned char acGUI_FontFont45_9EBB[246] = { /* code 9EBB */
  ________,________,______XX,________,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,____XXXX,X_______,________,________,
  ________,________,_____XXX,X_______,________,________,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  ____XXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,XXXXXXXX,X_______,
  _____XXX,X_______,________,________,________,________,
  _____XXX,X_______,________,________,________,________,
  _____XXX,X______X,XXXX____,_____XXX,XX______,________,
  _____XXX,X______X,XXXX____,_____XXX,X_______,________,
  _____XXX,X______X,XXXX____,_____XXX,X_______,________,
  _____XXX,X______X,XXXX____,_____XXX,X_______,________,
  _____XXX,X_______,XXXX____,_____XXX,X_______,________,
  _____XXX,X_______,XXXX____,_____XXX,X_______,________,
  _____XXX,X_XXXXXX,XXXXXXX_,XXXXXXXX,XXXXXXXX,________,
  _____XXX,X_XXXXXX,XXXXXXX_,XXXXXXXX,XXXXXXXX,________,
  _____XXX,X_XXXXXX,XXXXXXX_,XXXXXXXX,XXXXXXXX,________,
  ____XXXX,X_____XX,XXXX____,____XXXX,XX______,________,
  ____XXXX,X_____XX,XXXX____,____XXXX,XX______,________,
  ____XXXX,X_____XX,XXXX____,___XXXXX,XXX_____,________,
  ____XXXX,X_____XX,XXXXXXX_,___XXXXX,XXX_____,________,
  ____XXXX,X____XXX,XXXXXXXX,___XXXXX,XXXX____,________,
  ____XXXX,_____XXX,XXXXXXXX,__XXXXXX,XXXX____,________,
  ____XXXX,____XXXX,XXXXXXXX,X_XXXXXX,XXXXX___,________,
  ____XXXX,____XXXX,XXXX_XXX,XXXXXXXX,XXXXX___,________,
  ____XXXX,___XXXXX,XXXX__XX,_XXXXXXX,XXXXXX__,________,
  ____XXXX,___XXXX_,XXXX____,XXXXXXXX,X_XXXXX_,________,
  ____XXXX,__XXXXX_,XXXX____,XXXX_XXX,X_XXXXXX,________,
  ___XXXXX,__XXXXX_,XXXX___X,XXXX_XXX,X__XXXXX,X_______,
  ___XXXX_,_XXXXX__,XXXX__XX,XXX__XXX,X___XXXX,XX______,
  ___XXXX_,XXXXX___,XXXX_XXX,XXX__XXX,X____XXX,XXX_____,
  ___XXXX_,XXXXX___,XXXXXXXX,XX___XXX,X____XXX,XX______,
  __XXXXX_,_XXX____,XXXX__XX,X____XXX,X_____XX,X_______,
  __XXXX__,__XX____,XXXX___X,X____XXX,X______X,X_______,
  _XXXXX__,________,XXXX____,_____XXX,X_______,________,
  _XXXXX__,_______X,XXXX____,_____XXX,X_______,________,
  _XXXX___,_______X,XXXX____,_____XXX,X_______,________,
  ___XX___,_______X,XXXX____,_____XXX,X_______,________,
  ________,_______X,XXXX____,_____XXX,X_______,________};

GUI_CONST_STORAGE GUI_CHARINFO_EXT GUI_FontFont45_CharInfo[41] = {
   {  21,  20,   1,  13,  24, acGUI_FontFont45_002B } /* code 002B, PLUS SIGN */
  ,{  21,   3,   1,  21,  24, acGUI_FontFont45_002D } /* code 002D, HYPHEN-MINUS */
  ,{   5,   4,   4,  34,  24, acGUI_FontFont45_002E } /* code 002E, FULL STOP */
  ,{  20,  31,   1,   8,  24, acGUI_FontFont45_0030 } /* code 0030, DIGIT ZERO */
  ,{  10,  30,   4,   8,  24, acGUI_FontFont45_0031 } /* code 0031, DIGIT ONE */
  ,{  20,  31,   1,   7,  24, acGUI_FontFont45_0032 } /* code 0032, DIGIT TWO */
  ,{  19,  31,   2,   7,  24, acGUI_FontFont45_0033 } /* code 0033, DIGIT THREE */
  ,{  22,  30,   1,   8,  24, acGUI_FontFont45_0034 } /* code 0034, DIGIT FOUR */
  ,{  20,  31,   1,   8,  24, acGUI_FontFont45_0035 } /* code 0035, DIGIT FIVE */
  ,{  20,  31,   2,   8,  24, acGUI_FontFont45_0036 } /* code 0036, DIGIT SIX */
  ,{  20,  30,   2,   8,  24, acGUI_FontFont45_0037 } /* code 0037, DIGIT SEVEN */
  ,{  20,  30,   1,   8,  24, acGUI_FontFont45_0038 } /* code 0038, DIGIT EIGHT */
  ,{  20,  30,   1,   8,  24, acGUI_FontFont45_0039 } /* code 0039, DIGIT NINE */
  ,{   5,  20,   9,  18,  24, acGUI_FontFont45_003A } /* code 003A, COLON */
  ,{  17,  20,   3,  18,  24, acGUI_FontFont45_0073 } /* code 0073, LATIN SMALL LETTER S */
  ,{  39,  41,   4,   3,  47, acGUI_FontFont45_4E50 } /* code 4E50 */
  ,{  43,  42,   1,   2,  47, acGUI_FontFont45_4F4D } /* code 4F4D */
  ,{  43,  41,   1,   2,  47, acGUI_FontFont45_505C } /* code 505C */
  ,{  42,  42,   2,   2,  47, acGUI_FontFont45_590D } /* code 590D */
  ,{  42,  42,   2,   2,  47, acGUI_FontFont45_59CB } /* code 59CB */
  ,{  39,  41,   4,   2,  47, acGUI_FontFont45_5B89 } /* code 5B89 */
  ,{  43,  41,   1,   2,  47, acGUI_FontFont45_5B9A } /* code 5B9A */
  ,{  40,  42,   3,   2,  47, acGUI_FontFont45_5B9E } /* code 5B9E */
  ,{  42,  42,   2,   2,  47, acGUI_FontFont45_5EA6 } /* code 5EA6 */
  ,{  42,  39,   2,   4,  47, acGUI_FontFont45_5F00 } /* code 5F00 */
  ,{  41,  42,   2,   2,  47, acGUI_FontFont45_62A4 } /* code 62A4 */
  ,{  41,  41,   3,   2,  47, acGUI_FontFont45_65F6 } /* code 65F6 */
  ,{  40,  40,   3,   2,  47, acGUI_FontFont45_671B } /* code 671B */
  ,{  41,  40,   2,   3,  47, acGUI_FontFont45_671F } /* code 671F */
  ,{  42,  38,   2,   3,  47, acGUI_FontFont45_6B62 } /* code 6B62 */
  ,{  41,  42,   3,   2,  47, acGUI_FontFont45_6C14 } /* code 6C14 */
  ,{  43,  42,   1,   2,  47, acGUI_FontFont45_6C27 } /* code 6C27 */
  ,{  41,  40,   1,   3,  47, acGUI_FontFont45_6D4B } /* code 6D4B */
  ,{  42,  41,   2,   2,  47, acGUI_FontFont45_6D53 } /* code 6D53 */
  ,{  42,  40,   2,   3,  47, acGUI_FontFont45_6E29 } /* code 6E29 */
  ,{  42,  38,   2,   5,  47, acGUI_FontFont45_7406 } /* code 7406 */
  ,{  42,  40,   2,   3,  47, acGUI_FontFont45_8BA1 } /* code 8BA1 */
  ,{  42,  41,   2,   3,  47, acGUI_FontFont45_8BBE } /* code 8BBE */
  ,{  42,  41,   2,   2,  47, acGUI_FontFont45_9189 } /* code 9189 */
  ,{  41,  38,   4,   5,  47, acGUI_FontFont45_9645 } /* code 9645 */
  ,{  44,  41,   1,   2,  47, acGUI_FontFont45_9EBB } /* code 9EBB */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop30 = {
   0x9EBB /* first character */
  ,0x9EBB /* last character  */
  ,&GUI_FontFont45_CharInfo[ 40] /* address of first character */
  ,(GUI_CONST_STORAGE GUI_FONT_PROP_EXT *)0 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop29 = {
   0x9645 /* first character */
  ,0x9645 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 39] /* address of first character */
  ,&GUI_FontFont45_Prop30 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop28 = {
   0x9189 /* first character */
  ,0x9189 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 38] /* address of first character */
  ,&GUI_FontFont45_Prop29 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop27 = {
   0x8BBE /* first character */
  ,0x8BBE /* last character  */
  ,&GUI_FontFont45_CharInfo[ 37] /* address of first character */
  ,&GUI_FontFont45_Prop28 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop26 = {
   0x8BA1 /* first character */
  ,0x8BA1 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 36] /* address of first character */
  ,&GUI_FontFont45_Prop27 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop25 = {
   0x7406 /* first character */
  ,0x7406 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 35] /* address of first character */
  ,&GUI_FontFont45_Prop26 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop24 = {
   0x6E29 /* first character */
  ,0x6E29 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 34] /* address of first character */
  ,&GUI_FontFont45_Prop25 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop23 = {
   0x6D53 /* first character */
  ,0x6D53 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 33] /* address of first character */
  ,&GUI_FontFont45_Prop24 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop22 = {
   0x6D4B /* first character */
  ,0x6D4B /* last character  */
  ,&GUI_FontFont45_CharInfo[ 32] /* address of first character */
  ,&GUI_FontFont45_Prop23 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop21 = {
   0x6C27 /* first character */
  ,0x6C27 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 31] /* address of first character */
  ,&GUI_FontFont45_Prop22 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop20 = {
   0x6C14 /* first character */
  ,0x6C14 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 30] /* address of first character */
  ,&GUI_FontFont45_Prop21 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop19 = {
   0x6B62 /* first character */
  ,0x6B62 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 29] /* address of first character */
  ,&GUI_FontFont45_Prop20 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop18 = {
   0x671F /* first character */
  ,0x671F /* last character  */
  ,&GUI_FontFont45_CharInfo[ 28] /* address of first character */
  ,&GUI_FontFont45_Prop19 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop17 = {
   0x671B /* first character */
  ,0x671B /* last character  */
  ,&GUI_FontFont45_CharInfo[ 27] /* address of first character */
  ,&GUI_FontFont45_Prop18 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop16 = {
   0x65F6 /* first character */
  ,0x65F6 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 26] /* address of first character */
  ,&GUI_FontFont45_Prop17 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop15 = {
   0x62A4 /* first character */
  ,0x62A4 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 25] /* address of first character */
  ,&GUI_FontFont45_Prop16 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop14 = {
   0x5F00 /* first character */
  ,0x5F00 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 24] /* address of first character */
  ,&GUI_FontFont45_Prop15 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop13 = {
   0x5EA6 /* first character */
  ,0x5EA6 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 23] /* address of first character */
  ,&GUI_FontFont45_Prop14 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop12 = {
   0x5B9E /* first character */
  ,0x5B9E /* last character  */
  ,&GUI_FontFont45_CharInfo[ 22] /* address of first character */
  ,&GUI_FontFont45_Prop13 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop11 = {
   0x5B9A /* first character */
  ,0x5B9A /* last character  */
  ,&GUI_FontFont45_CharInfo[ 21] /* address of first character */
  ,&GUI_FontFont45_Prop12 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop10 = {
   0x5B89 /* first character */
  ,0x5B89 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 20] /* address of first character */
  ,&GUI_FontFont45_Prop11 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop9 = {
   0x59CB /* first character */
  ,0x59CB /* last character  */
  ,&GUI_FontFont45_CharInfo[ 19] /* address of first character */
  ,&GUI_FontFont45_Prop10 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop8 = {
   0x590D /* first character */
  ,0x590D /* last character  */
  ,&GUI_FontFont45_CharInfo[ 18] /* address of first character */
  ,&GUI_FontFont45_Prop9 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop7 = {
   0x505C /* first character */
  ,0x505C /* last character  */
  ,&GUI_FontFont45_CharInfo[ 17] /* address of first character */
  ,&GUI_FontFont45_Prop8 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop6 = {
   0x4F4D /* first character */
  ,0x4F4D /* last character  */
  ,&GUI_FontFont45_CharInfo[ 16] /* address of first character */
  ,&GUI_FontFont45_Prop7 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop5 = {
   0x4E50 /* first character */
  ,0x4E50 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 15] /* address of first character */
  ,&GUI_FontFont45_Prop6 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop4 = {
   0x0073 /* first character */
  ,0x0073 /* last character  */
  ,&GUI_FontFont45_CharInfo[ 14] /* address of first character */
  ,&GUI_FontFont45_Prop5 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop3 = {
   0x0030 /* first character */
  ,0x003A /* last character  */
  ,&GUI_FontFont45_CharInfo[  3] /* address of first character */
  ,&GUI_FontFont45_Prop4 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop2 = {
   0x002D /* first character */
  ,0x002E /* last character  */
  ,&GUI_FontFont45_CharInfo[  1] /* address of first character */
  ,&GUI_FontFont45_Prop3 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT_PROP_EXT GUI_FontFont45_Prop1 = {
   0x002B /* first character */
  ,0x002B /* last character  */
  ,&GUI_FontFont45_CharInfo[  0] /* address of first character */
  ,&GUI_FontFont45_Prop2 /* pointer to next GUI_FONT_PROP_EXT */
};

GUI_CONST_STORAGE GUI_FONT GUI_FontFont45 = {
   GUI_FONTTYPE_PROP_EXT /* type of font    */
  ,45 /* height of font  */
  ,45 /* space of font y */
  ,1 /* magnification x */
  ,1 /* magnification y */
  ,{&GUI_FontFont45_Prop1}
  ,39 /* Baseline */
  ,20 /* Height of lowercase characters */
  ,30 /* Height of capital characters */
};

