/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.44                          *
*        Compiled Nov 10 2017, 08:53:57                              *
*        (c) 2017 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/

// USER START (Optionally insert additional includes)
// USER END

#include "DIALOG.h"
#include "GUI.h"
#include "GlobalVar.h"
#include "stdio.h"
#include "stdlib.h"


/*********************************************************************
*
*       Defines
*
**********************************************************************
*/
#define ID_WINDOW_0 (GUI_ID_USER + 0x04)
#define ID_BUTTON_0 (GUI_ID_USER + 0x05)
#define ID_TEXT_0 (GUI_ID_USER + 0x06)
#define ID_TEXT_1 (GUI_ID_USER + 0x07)
#define ID_TEXT_2 (GUI_ID_USER + 0x08)
#define ID_TEXT_3 (GUI_ID_USER + 0x09)
#define ID_BUTTON_1 (GUI_ID_USER + 0x0A)
#define ID_BUTTON_2 (GUI_ID_USER + 0x0B)
#define ID_BUTTON_3 (GUI_ID_USER + 0x0C)
#define ID_TEXT_4 (GUI_ID_USER + 0x0D)
#define ID_TEXT_5 (GUI_ID_USER + 0x0E)
#define ID_TEXT_6 (GUI_ID_USER + 0x0F)
#define ID_TEXT_7 (GUI_ID_USER + 0x10)
#define ID_TEXT_8 (GUI_ID_USER + 0x11)
#define ID_BUTTON_4 (GUI_ID_USER + 0x12)

extern GUI_CONST_STORAGE GUI_FONT GUI_FontFont45;
// USER START (Optionally insert additional defines)
#define EXTERN_FONT &GUI_FontFont45
// USER END

/*********************************************************************
*
*       Static data
*
**********************************************************************
*/

// USER START (Optionally insert additional static data)
WM_HWIN _hWin;
GUI_COLOR _bkColor;
//BUTTON_SKINFLEX_PROPS* pPropsStart;
//BUTTON_SKINFLEX_PROPS* pPropsWait;
//BUTTON_SKINFLEX_PROPS* pPropsStop;
//BUTTON_SKINFLEX_PROPS* pProps;
// USER END

/*********************************************************************
*
*       _aDialogCreate
*/
//static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
//  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 800, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "TempAdd", ID_BUTTON_0, 330, 150, 120, 60, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 30, 150, 160, 60, 0, 0x64, 0 },
//  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 30, 230, 160, 60, 0, 0x64, 0 },
//  { TEXT_CreateIndirect, "time2", ID_TEXT_2, 30, 400, 120, 60, 0, 0x64, 0 },
//  { TEXT_CreateIndirect, "time3", ID_TEXT_3, 30, 580, 120, 60, 0, 0x64, 0 },
//  { BUTTON_CreateIndirect, "Start2", ID_BUTTON_1, 330, 400, 120, 60, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "Start3", ID_BUTTON_2, 330, 580, 120, 60, 0, 0x0, 0 },
//  { BUTTON_CreateIndirect, "TempSub", ID_BUTTON_3, 330, 230, 120, 60, 0, 0x0, 0 },
//  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 30, 60, 180, 60, 0, 0x64, 0 },
//  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 210, 150, 120, 60, 0, 0x64, 0 },
//  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 210, 230, 120, 60, 0, 0x64, 0 },
//  { TEXT_CreateIndirect, "TimeDisp2", ID_TEXT_7, 160, 400, 130, 60, 0, 0x64, 0 },
//  { TEXT_CreateIndirect, "TimeDisp3", ID_TEXT_8, 160, 580, 130, 60, 0, 0x64, 0 },
//  { BUTTON_CreateIndirect, "Open1st", ID_BUTTON_4, 330, 70, 120, 60, 0, 0x0, 0 },
//  // USER START (Optionally insert additional widgets)
//  // USER END
//};

static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] = {
  { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 800, 480, 0, 0x0, 0 },
  { BUTTON_CreateIndirect, "TempAdd", ID_BUTTON_0, 330, 200, 120, 60, 0, 0x0, 0 },  // ?????
  { TEXT_CreateIndirect, "Text", ID_TEXT_0, 30, 200, 160, 60, 0, 0x64, 0 },         //  “????”
  { TEXT_CreateIndirect, "Text", ID_TEXT_1, 30, 310, 160, 60, 0, 0x64, 0 },         //  “????”
  { TEXT_CreateIndirect, "time2", ID_TEXT_2, 500, 50, 120, 60, 0, 0x64, 0 },       // ???????
  { TEXT_CreateIndirect, "time3", ID_TEXT_3, 500, 270, 120, 60, 0, 0x64, 0 },       // ???????
  { BUTTON_CreateIndirect, "Start2", ID_BUTTON_1, 650, 90, 120, 60, 0, 0x0, 0 }, // ???????
  { BUTTON_CreateIndirect, "Start3", ID_BUTTON_2, 650, 310, 120, 60, 0, 0x0, 0 }, // ???????
  { BUTTON_CreateIndirect, "TempSub", ID_BUTTON_3, 330, 310, 120, 60, 0, 0x0, 0 },  //  ?????
  { TEXT_CreateIndirect, "Text", ID_TEXT_4, 30, 90, 180, 60, 0, 0x64, 0 },          //  “??”
  { TEXT_CreateIndirect, "Text", ID_TEXT_5, 200, 200, 120, 60, 0, 0x64, 0 },        //  ????
  { TEXT_CreateIndirect, "Text", ID_TEXT_6, 200, 310, 120, 60, 0, 0x64, 0 },        //  ????
  { TEXT_CreateIndirect, "TimeDisp2", ID_TEXT_7, 510, 120, 130, 60, 0, 0x64, 0 },  // ???????
  { TEXT_CreateIndirect, "TimeDisp3", ID_TEXT_8, 510, 340, 130, 60, 0, 0x64, 0 },  // ???????
  { BUTTON_CreateIndirect, "Open1st", ID_BUTTON_4, 330, 90, 120, 60, 0, 0x0, 0 },   // ??????
  // USER START (Optionally insert additional widgets)
  // USER END
};

/*********************************************************************
*
*       Static code
*
**********************************************************************
*/

// USER START (Optionally insert additional static code)
// USER END

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE* pMsg) {
    WM_HWIN hItem;
    int     NCode;
    int     Id;
    // USER START (Optionally insert additional variables)
    // USER END

    switch (pMsg->MsgId) {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Window'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, 0x00000000);
        //
        // Initialization of '?????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_0);
        BUTTON_SetFont(hItem, EXTERN_FONT);
        BUTTON_SetText(hItem, "+");
        //BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_RED);
        //
        // Initialization of '“??”'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_0);
        TEXT_SetText(hItem, "\xe8\xae\xbe\xe5\xae\x9a:");
        TEXT_SetFont(hItem, EXTERN_FONT);
        TEXT_SetTextColor(hItem, 0x00FFFFFF);
        //
        // Initialization of '“??”'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_1);
        TEXT_SetFont(hItem, EXTERN_FONT);
        TEXT_SetText(hItem, "\xe5\xae\x9e\xe6\xb5\x8b:");
        TEXT_SetTextColor(hItem, 0x00FFFFFF);
        //
        // Initialization of '???????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_2);
        TEXT_SetText(hItem, "\xe8\xae\xa1\xe6\x97\xb6:");
        TEXT_SetFont(hItem, EXTERN_FONT);
        TEXT_SetTextColor(hItem, 0x00FFFFFF);
        //
        // Initialization of '???????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_3);
        TEXT_SetFont(hItem, EXTERN_FONT);
        TEXT_SetText(hItem, "\xe8\xae\xa1\xe6\x97\xb6:");
        TEXT_SetTextColor(hItem, 0x00FFFFFF);
        //
        // Initialization of '???????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_1);
        BUTTON_SetText(hItem, "\xe9\xba\xbb\xe9\x86\x89");
        BUTTON_SetFont(hItem, EXTERN_FONT);
        //BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_RED);
        //
        // Initialization of '???????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_2);
        BUTTON_SetText(hItem, "\xe5\xae\x89\xe4\xb9\x90");
        BUTTON_SetFont(hItem, EXTERN_FONT);
        //BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_RED);
        //
        // Initialization of '?????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_3);
        BUTTON_SetFont(hItem, EXTERN_FONT);
        BUTTON_SetText(hItem, "-");
        //
        // Initialization of '“??”'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_4);
        TEXT_SetFont(hItem, EXTERN_FONT);
        TEXT_SetText(hItem, "\xe6\xb8\xa9\xe5\xba\xa6");
        TEXT_SetTextColor(hItem, (0x00FFFFFF));
        //
        // Initialization of '????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_5);
        TEXT_SetText(hItem, "0");
        TEXT_SetFont(hItem, EXTERN_FONT);
        TEXT_SetTextColor(hItem, (0x00FFFFFF));
        //
        // Initialization of '????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_6);
        TEXT_SetFont(hItem, EXTERN_FONT);
        TEXT_SetText(hItem, "0");
        TEXT_SetTextColor(hItem, (0x00FFFFFF));
        //
        // Initialization of '???????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_7);
        TEXT_SetTextColor(hItem, (0x00FF0000));
        TEXT_SetText(hItem, "0");
        TEXT_SetFont(hItem, EXTERN_FONT);
        //
        // Initialization of '???????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_TEXT_8);
        TEXT_SetText(hItem, "0");
        TEXT_SetTextColor(hItem, (0x00FF0000));
        TEXT_SetFont(hItem, EXTERN_FONT);
        //
        // Initialization of '??????'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_4);
        BUTTON_SetText(hItem, "\xe6\x8a\xa4\xe7\x90\x86");
        BUTTON_SetFont(hItem, EXTERN_FONT);
        //BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_RED);
        // USER START (Optionally insert additional code for further widget initialization)
        // USER END
        _bkColor = BUTTON_GetBkColor(hItem, BUTTON_CI_UNPRESSED);
        break;
    case WM_NOTIFY_PARENT:
        Id = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        switch (Id) {
        case ID_BUTTON_0: // Notifications sent by 'TempAdd'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                expect_temp += 1;
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_1: // Notifications sent by 'Start2'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                if (gui_time2_flag == 0) {
                    gui_time2_flag = 2;
                    hItem = WM_GetDialogItem(_hWin, ID_BUTTON_1);
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_GREEN);
                    //BUTTON_SetText(hItem, "\xe5\x81\x9c\xe6\xad\xa2");
                }
                else if (gui_time2_flag == 1){
                    gui_time2_flag = 2;
                    hItem = WM_GetDialogItem(_hWin, ID_BUTTON_1);
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_YELLOW);
                    //BUTTON_SetText(hItem, "\xe5\xa4\x8d\xe4\xbd\x8d");
                }
                else if (gui_time2_flag == 2) {
                    gui_time2_flag = 0;
                    hItem = WM_GetDialogItem(_hWin, ID_BUTTON_1);
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, _bkColor);
                    //BUTTON_SetText(hItem, "\xe5\xbc\x80\xe5\xa7\x8b");
                }
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_2: // Notifications sent by 'Start3'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                if (gui_time3_flag == 0) {
                    gui_time3_flag = 2;
                    hItem = WM_GetDialogItem(_hWin, ID_BUTTON_2);
                    //BUTTON_SetText(hItem, "\xe5\x81\x9c\xe6\xad\xa2");
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_GREEN);
                }
                else if (gui_time3_flag == 1) {
                    gui_time3_flag = 2;
                    hItem = WM_GetDialogItem(_hWin, ID_BUTTON_2);
                    //BUTTON_SetText(hItem, "\xe5\xa4\x8d\xe4\xbd\x8d");
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_YELLOW);
                }
                else if (gui_time3_flag == 2) {
                    gui_time3_flag = 0;
                    hItem = WM_GetDialogItem(_hWin, ID_BUTTON_2);
                    //BUTTON_SetText(hItem, "\xe5\xbc\x80\xe5\xa7\x8b");
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, _bkColor);
                }
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
        case ID_BUTTON_3: // Notifications sent by 'TempSub'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                expect_temp -= 1;
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        case ID_BUTTON_4: // Notifications sent by 'Open1st'
            switch (NCode) {
            case WM_NOTIFICATION_CLICKED:
                // USER START (Optionally insert code for reacting on notification message)
                // USER END
                break;
            case WM_NOTIFICATION_RELEASED:
                // USER START (Optionally insert code for reacting on notification message)
                if (gui_floor1_flag == 0) {
                    gui_floor1_flag = 1;
                    hItem = WM_GetDialogItem(_hWin, ID_BUTTON_4);
                    //BUTTON_SetText(hItem, "\xe5\x81\x9c\xe6\xad\xa2");
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, GUI_GREEN);
                }
                else if (gui_floor1_flag == 1) {
                    gui_floor1_flag = 0;
                    hItem = WM_GetDialogItem(_hWin, ID_BUTTON_4);
                    //BUTTON_SetText(hItem, "\xe5\xbc\x80\xe5\xa7\x8b");
                    BUTTON_SetBkColor(hItem, BUTTON_CI_UNPRESSED, _bkColor);
                }
                // USER END
                break;
                // USER START (Optionally insert additional code for further notification handling)
                // USER END
            }
            break;
            // USER START (Optionally insert additional code for further Ids)
            // USER END
        }
        break;
        // USER START (Optionally insert additional message handling)
        // USER END
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       Public code
*
**********************************************************************
*/
/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateWindow(void);
WM_HWIN CreateWindow(void) {
    WM_HWIN hWin;
		BUTTON_SetDefaultSkinClassic();
    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

// USER START (Optionally insert additional public code)
// USER END

/*************************** End of file ****************************/



/*********************************************************************
*
*       _cbBk
*/
static void _cbBk(WM_MESSAGE* pMsg) {
    switch (pMsg->MsgId) {
    case WM_PAINT:

        break;
    default:
        WM_DefaultProc(pMsg);
    }
}

char disp_buf[10];
GUI_HWIN disp_text_item;

void gui_init(void) {
    WM_SetCreateFlags(WM_CF_MEMDEV);
    WM_MOTION_Enable(1);
    WM_MULTIBUF_Enable(1);
    GUI_Init();
    GUI_UC_SetEncodeUTF8(); // Enable UTF8 decoding
    //
    // Set a callback for the background window
    //
    WM_SetCallback(WM_HBKWIN, _cbBk);
    _hWin = CreateWindow();
}

void gui_loop(void) {
    GUI_Delay(50);

    disp_text_item = WM_GetDialogItem(_hWin, ID_TEXT_7);
    sprintf(disp_buf, "%.1f s", (float)gui_time2_count / 100);
    TEXT_SetText(disp_text_item, disp_buf);

    disp_text_item = WM_GetDialogItem(_hWin, ID_TEXT_8);
    sprintf(disp_buf, "%.1f s", (float)gui_time3_count / 100);
    TEXT_SetText(disp_text_item, disp_buf);

    disp_text_item = WM_GetDialogItem(_hWin, ID_TEXT_5);
    sprintf(disp_buf, "%.1f", expect_temp);
    TEXT_SetText(disp_text_item, disp_buf);

    disp_text_item = WM_GetDialogItem(_hWin, ID_TEXT_6);
    sprintf(disp_buf, "%.1f", real_temp);
    TEXT_SetText(disp_text_item, disp_buf);
}
/*********************************************************************
*
*       MainTask
*/
void MainTask(void) {

    gui_init();
    //
    // Stay alive loop
    //
    while (1) {
        gui_loop();
    }
}
